### ISSUE TITLE
Any plans to upload the conventions code?

### ISSUE THREAD

**Issue by dnetguru** [graphql-dotnet/conventions#1]
It has been a while since the conventions code has been removed from the graphql-dotnet repository and I have been wondering for a while if the conventions code is going to be uploaded here any time soon.

Thanks!

**Comment by tlil** [comment]
Final rounds of testing on my end here now, so I expect to have it up by the end of next week. cc @moserware, @zhech2, @scmccart, @SpencerMacKinnon, @holm0563 @joemcbride.

**Comment by joemcbride** [comment]
There are a couple forks floating around of the old code available if you're interested in looking at it.

https://github.com/joemcbride/conventions

**Comment by tlil** [comment]
Yeah that's _very_ outdated now ;p I essentially scrapped most of it and refactored it all.

**Comment by dnetguru** [comment]
Let me know if I can be of any help.

**Comment by tlil** [comment]
@dNetGuru Initial version is up. I'm adding in Appveyor build and NuGet packaging right now.
