### ISSUE TITLE
Problems with test solution latest XPROJ

### ISSUE THREAD

**Issue by ronnyek** [graphql-dotnet/conventions#10]
I don't know why but I absolutely couldnt get unit tests to run inside of visual studio after getting latest. I attempted to fix what I believed to be a bug, but couldnt verify with tests. Out of the box, it seems like the xproj files contain invalid paths, and the test project xproj has a bunch of white space at the beginning of the file which causes vs.net to be extremely unhappy.

After manually fixing the file, I manually set bin outputs (something like .\bin\) and was able to get tests working from command line (or at least it wasn't complaining about finding the graphql-dotnet.conventions assembly). "dotnet test" would then execute saying 230 tests, but couldn't really tell if the tests themselves were running. Still couldnt execute tests from within vs.net

```
=== TEST EXECUTION SUMMARY ===
   GraphQL.Conventions.Tests  Total: 230, Errors: 0, Failed: 0, Skipped: 0, Time: 0.631s
Project GraphQL.Conventions (.NETFramework,Version=v4.5) was previously compiled. Skipping compilation.
Project GraphQL.Conventions.Tests (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
```

**Comment by tlil** [comment]
I've only tested the project compilation from commandline on Windows, and from commandline and Visual Studio Code on macOS. Will take a look at it over the weekend.

**Comment by ronnyek** [comment]
I'd be more than happy to contribute some unit tests that could both be used to verify conventions lib is doing what its supposed to, as well as further test for future... but I cant easily debug.

**Comment by tlil** [comment]
@ronnyek i've included project files using the new `.csproj` format for .NET Core now (in addition to the `.proj` files for now).

FYI, there's also this to be aware of: https://github.com/OmniSharp/omnisharp-vscode/issues/1100

**Comment by tlil** [comment]
@ronnyek will close this issue as I'm already addressing it through: https://github.com/graphql-dotnet/conventions/issues/30. Sorry about the slow response. Will get the unit tests set up properly for Visual Studio as well. PR pending.
