### ISSUE TITLE
Query batching

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#101]
Is there any plan for supporting [query batching](http://dev.apollodata.com/core/network.html#BatchingExplained)? It [appears to be supported](https://github.com/graphql-dotnet/graphql-dotnet/issues/398) by the graphql-dotnet package library, if just in principal by parsing them and [executing them individually](https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay/Http/RequestExecutor.cs#L26).

On the conventions side it looks like [Executor.WithRequest](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Adapters/Engine/GraphQLExecutor.cs#L43) specifically expects to deserialize a single query.

Is this just a case of needing to pre-parse it like with the main library? Would you accept a PR that includes a built-in way to do this?

Thanks :)

**Comment by tlil** [comment]
..... sorry for the late response first of all!

Yes, you could just pre-parse it and execute for each operation X1 ... Xn :-) If you fancy submitting a PR, I'll take a look :+1:

**Comment by infogulch** [comment]
So I had another look at this and the [Deserializer implementation](https://github.com/graphql-dotnet/relay/blob/master/src/GraphQL.Relay/Http/Deserializer.cs) in GraphQL.NET comes from GraphQL.Relay.  It basically tries to deserialize either a single json query object `{query: "...", variables: {}}` or an array of such objects.

Would you accept an implementation that adds a dependency on GraphQL.Relay for that implementation, or would you prefer a copied/duplicate implementation?

**Comment by tlil** [comment]
That'd be fine, yes, @infogulch.

BTW: I'm currently reworking some of the other bits, so will keep this in mind.
