### ISSUE TITLE
Problems parsing ID's in sample webapp

### ISSUE THREAD

**Issue by ronnyek** [graphql-dotnet/conventions#102]
Greetings... I was just trying to get back up to date on the conventions project. I went ahead and started up the endpoint and connected graphiql and started issuing commands. Seems like things that require specifying ID's never want to parse no matter what you plugin and was hoping for a quick pointer to something I am doing wrong.

``` js
// both these queries are being executed via viewer, but have exact same result against both just regular query object
{
  viewer{
    author(id: 1){
      firstName
      lastName
    }
  }
}
// results in"
 {"errors":[{"message":"Argument \"id\" has invalid value 1.\nExpected type \"ID\", found 1.","locations":[{"line":3,"column":12}],"code":"VALIDATION_ERROR"}]}

// if I try and change the id's into quoted ids
{
  viewer{
    author(id: "1"){
      firstName
      lastName
    }
  }
}
// I end up with the following
{"errors":[{"message":"Unable to decode identifier '1'.","code":"ARGUMENT"}]}
```

**Comment by infogulch** [comment]
What's the code of your resolver? That's probably the most relevant part here.

Are you using the [GraphQL.Conventions Id struct](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Types/Id.cs)? It acts differently than just a string.

**Comment by tlil** [comment]
Hi @ronnyek - the type `ID` is used for identifiers that are normally formed from the base64 encoded version of a string `"<TypeName>:<UnderlyingID>"`. So for an identifier of an author #1, it would be `base64("Author:1")`. You can read up on the matter here:
 - http://facebook.github.io/graphql/October2016/#sec-ID
 - https://facebook.github.io/relay/docs/en/graphql-server-specification.html#object-identification

This is for cacheability, etc. If you don't want to use this convention, you'd have to use `String` or `Int` as a type instead.

**Comment by infogulch** [comment]
Speaking for myself, I really like this convention. Besides cacheability, it means you can't accidentally use an id from the wrong source and it continues chugging along without blinking.

I also use integer ids, which can be tedious to extract from an `Id` type. So I made some extension methods to help alleviate that pain. I actually use all of these in a project that I'm currently working on:

```C#
using System;
using GraphQL.Conventions;

public static class IdExtensions
{
    // ToId<T> directly converts any integer to an Id of the specified type.
    public static Id ToId<T>(this int? id)
    {
        return id.HasValue ? Id.New<T>(id.Value) : null;
    }

    public static Id ToId<T>(this int id)
    {
        return Id.New<T>(id);
    }

    // IntIdForType<T> tries to parse Id as as an int of the specified type.
    // It never throws and returns an explicitly nullable result in case of any error or missing data.
    // It accepts a default value in case the id failed to resolve as the specified type or the result
    // failed to parse as an int.
    //
    // The inputs are designed with flexible nullability to easily support inputs with optional arguments.
    public static int? IntIdForType<T>(this Id? id, int? def)
    {
        try
        {
            if (id == null)
                return def;
            var sid = id?.IdentifierForType<T>();
            if (string.IsNullOrEmpty(sid))
                return def;
            int o;
            return int.TryParse(sid, out o) ? (int?)o : def;
        }
        catch (ArgumentException)
        {
            return def;
        }
    }

    // These are all nullability- and no-default- variations that call the original above for convenience.
    public static int IntIdForType<T>(this Id? id, int def) => (int)IntIdForType<T>(id, (int?)def);

    public static int? IntIdForType<T>(this Id id, int? def) => IntIdForType<T>((Id?)id, def);

    public static int? IntIdForType<T>(this Id? id) => IntIdForType<T>(id, null);

    public static int? IntIdForType<T>(this Id id) => IntIdForType<T>((Id?)id, null);
}
```

My names for things usually leave something to be desired, feel free to suggest better ones. And I know dubious extension methods are typically frowned upon, so please be gentle when you're roasting me for this. 🤣

**Comment by ronnyek** [comment]
Oh I have no preference, was just confused about what it was looking for, I had example schemas I would connect graphiql and it was looking for int or something for an id. I think this is reasonable, and it answers my question
