### ISSUE TITLE
EnumerableExtensions.Map does not exists

### ISSUE THREAD

**Issue by TheAifam5** [graphql-dotnet/conventions#111]
Hey,
In the following versions of GraphQL 2.2.0-2.3.0, the "Map" extension for IEnumerable does not exists anymore which throws an exception:
```
Method not found: 'System.Collections.Generic.IEnumerable`1<!!0> GraphQL.EnumerableExtensions.Map(System.Collections.IEnumerable, System.Func`2<System.Object,!!0>)'.
```

Affected line:
https://github.com/graphql-dotnet/conventions/blob/2a5397707d50e5aa006e04780d127e3db3b9f212/src/GraphQL.Conventions/Attributes/Execution/Unwrappers/CollectionUnwrapper.cs#L21

Commit from graphql-dotnet:
https://github.com/graphql-dotnet/graphql-dotnet/commit/952b4ef6950e51bbfe009354f0520180c343e8d4#diff-992f25705b68d8de6f63113661c3a037

Regards,
TheAifam5

**Comment by BilyachenkoOY** [comment]
Hey @tlil, any news on this issue?

**Comment by tlil** [comment]
See @cphillips83's PR: https://github.com/graphql-dotnet/conventions/pull/130

Just merged :-)
