### ISSUE TITLE
Unable to add custom scalar type - Maybe<T> for partial model updates.

### ISSUE THREAD

**Issue by john-rubin** [graphql-dotnet/conventions#115]
Greetings!

I was attempting to utilize a custom `Maybe<T>` as a parameter on an input type, to easily check for set/unset parameters in a partial update, but I'm having some trouble, and though I've tried registering it as a custom scalar type, those registrations don't end up on the generated schema.

Is there some way to do this?  I see there are ways of adding custom type registrations in the GraphTypeAdapter, and the TypeResolver, both of which are set when adding custom scalar types via the `public GraphQLEngine RegisterScalarType<TType, TGraphType>(string name = null);` call, but after doing this for several Maybe<T> types, pointed at already implemented GraphTypes, the result was the same.  
The Maybe<T> parameter shows up named as `InputGraphType`1`, even after I've specified a name for this type.

**Comment by tlil** [comment]
Hi @john-rubin,

Could you point me to a snippet of what you're trying to do, and I'll take a look?

Cheers

**Comment by john-rubin** [comment]
Hey @tlil!  Sorry it took me a while to get back to you.

I was trying to make a convenient partial update for a model using a custom type.  I wanted to know when some properties are set, and when some are not, so I can perform updates to the properties that were set, and ignore those that were not.  This was necessary, because the model's primitive members are nullable.

The custom type I wanted to register was a `Maybe<T>`.  It just tracked whether or not the T's value was set, or unset.

For instance:
`Maybe<string> SomeString { get; set; }`

Would be set by:
`
{
 mutation someMutation {
   mutateSomeModel(input:{
    someString: {
      value: "this string is set"
    }
   })
 }
}
` 

The `Maybe<T>`'s name was showing up as ``InputGraphType`1``.  I figured I need to register this type as a custom scalar type, similar to the `Id<T>` and `NonNull<T>` types.  However, my attempts at doing this failed.

**Comment by tlil** [comment]
Closing as dup of #128. Will follow up there.
