### ISSUE TITLE
Proper way to expose a Date-only field ?

### ISSUE THREAD

**Issue by leddt** [graphql-dotnet/conventions#117]
How can I have a date field on a type that would get serialized and de-serialized as date-only (yyyy-mm-dd)?

In graphql-dotnet there is the `DateGraphType` that I believe can be used for this purpose, but how can I make use of this in Conventions?

**Comment by leddt** [comment]
The `GraphTypeAdapter` class appears to have considerations in place for `DateGraphType`, but I can't figure out how it's supposed to be used.

**Comment by leddt** [comment]
After taking more time to understand the code, I've created this attribute:
```
    public class GraphTypeNameAttribute : MetaDataAttributeBase
    {
        private readonly string name;

        public GraphTypeNameAttribute(string name)
        {
            this.name = name;
        }

        public override void DeriveMetaData(GraphEntityInfo entity)
        {
            base.DeriveMetaData(entity);
            entity.Type.Name = name;
        }
    }
```

And I defined my property like this:
```
[GraphTypeName("Date")]
public DateTime ExpectedStartDate { get; set; }
```

It appears to work as intended. Is that a good way to achieve this?

**Comment by tlil** [comment]
That's one way of achieving it, yes. Otherwise, you'd need an explicitly named type, `Date`. This has slipped through - will add it to the to-do list and get something into the next version.

Along the lines of your solution, you could also consider creating a less generic attribute, say `[Date]`. :-)

**Comment by leddt** [comment]
Thanks. Indeed, I ended up creating a `DateOnly` attribute deriving from my `GraphTypeName`. Much cleaner that way!

**Comment by leddt** [comment]
I just realized that the attribute I came up with will modify the underlying `GraphTypeInfo` that is shared across all `DateTime` properties on my schema. This means that all `DateTime` properties are now exposed as `Date`, regardless of whether they have the `DateOnly` attribute or not.

So I changed my code to look like this:
```
    public class GraphTypeNameAttribute : MetaDataAttributeBase
    {
        private readonly string name;

        public GraphTypeNameAttribute(string name)
        {
            this.name = name;
        }

        public override void DeriveMetaData(GraphEntityInfo entity)
        {
            base.DeriveMetaData(entity);
            entity.Type = customTypes.GetOrAdd(name, n => CreateCustomType(entity, n));
        }

        private static readonly ConcurrentDictionary<string, GraphTypeInfo> customTypes = new ConcurrentDictionary<string, GraphTypeInfo>();
        private static GraphTypeInfo CreateCustomType(GraphEntityInfo entity, string n)
        {
            return new GraphTypeInfo(entity.TypeResolver, entity.Type.TypeRepresentation) {
                Name = n
            };
        }
    }

    public class DateOnlyAttribute : GraphTypeNameAttribute
    {
        public DateOnlyAttribute() : base("Date") {}
    }
```

It appears to be working as intended, but it feels really hacky. Native support for `Date` in the conventions library would make me feel a lot better about this 😆

**Comment by tlil** [comment]
Yep, it's on my TODO list :)

**Comment by RRKeegan** [comment]
I would like to implement this same functionality to expose the date without a time component. Have there been underlying conventions library changes to allow this? If not I'll try following the example provided by @leddt

**Comment by sungam3r** [comment]
graphql-dotnet now [supports](https://graphql-dotnet.github.io/docs/getting-started/schema-types) 5 such types.

**Comment by RRKeegan** [comment]
While the core library supports the Date type, I believe this issue is specific to the conventions library.  So rather than using `Field<Date>(..)` nomenclature, This library provides the ability to use POCOs e.g.: `public DateTime DateOfBirth {get; set;}`. If there the conventions library now provides the capability to expose a Date-only field I'd be very interested in seeing an example.

**Comment by tlil** [comment]
https://github.com/graphql-dotnet/conventions/blob/91b49a4f9f39bc31c0846a608c582f7e88832d33/src/GraphQL.Conventions/Adapters/GraphTypeAdapter.cs#L140

Support for Date, DateTime, DateTimeOffset and TimeSpan have been added. For any missing ones, feel free to raise a PR.

**Comment by leddt** [comment]
Unless I'm mistaken, there is no _clean_ way to use this, as there is no `Date` type in .NET. Hence my workaround using a `DateOnlyAttribute`, which has it's own share of issues.

Or maybe I'm wrong and there is a way. In that case, could you provide some sample code to demonstrate how we can use the `DateGraphType`?

**Comment by tlil** [comment]
Yep, that's true. `Date` above is hinging on an implementation of `Date` that's compatible with `DateGraphType`, which is not straight-forward given the fact that the latter pattern-matches on the type `DateTime`.

The limitation is in the .NET type system, so for now your "best" option is something like `DateOnlyAttribute`. There is a proposal in **corefxlab**, https://github.com/dotnet/corefxlab/blob/master/src/System.Time/System/Date.cs, but that's obviously not integrated in any way.

**Comment by leddt** [comment]
I wonder if there would be a way to integrate with [NodaTime](https://nodatime.org/). We could then expose meaningful types such as `LocalDate`, `ZonedDateTime`, `Instant`, etc.

**Comment by leddt** [comment]
Looks like this already came up in #160. It would probably be pretty simple to develop a package like `GraphQL.Conventions.NodaTime`. I'll try to look into it, if I find the time :)

**Comment by tlil** [comment]
Yep, it should be pretty simple :) Mapping in `GraphTypeAdapter`, and a separate `*GraphType` implementation should get you going :+1:

**Comment by leddt** [comment]
Well, that was pretty easy! I found the [GraphQL.NodaTime](https://github.com/shoooe/graphql-nodatime) package, which already implements the graph types. I just created a simple extension method to register them all as scalars. Here's my package: 
https://github.com/leddt/GraphQL.Conventions.NodaTime

**Comment by tlil** [comment]
🎉 Nice one :+1:
