### ISSUE TITLE
Move error transformation to dedicated class

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#119]
Hi Tommy, we're playing with the idea to move the custom error transformations (see https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs#L288) to a separate class, which can be easily replaced by a new method called `WithErrorTransformation` or `WithErrorTransformer` f.e.

What would you think about that?

**Comment by tlil** [comment]
Yes, that sounds great. Would gladly accept a PR for that. :-)

**Comment by tlil** [comment]
Closing this since you've raised #122 - thanks
