### ISSUE TITLE
Uneccessary execution error wrapping

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#120]
After rewriting my original solution using GraphQL.Conventions I fall into the issue that I can't handle errors as easily as before. For example, this code is not working anymore:
```cs
// filtering by type
var criticalErros = result.Errors?.Except(result.Errors.OfType<DeprecatedNodeExecutionError>());
// or filtering by custom code
var criticalErros = result.Errors?.Where(e => e.Code != "DEPRECATED_NODE");
```

This is because of some two-lever errors wrapping which is made in [GraphQLEngine.cs#L289](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs#L289). 
- So, is there any reason for such wrapping which makes it harder to determine my errors later and changes some data (`ExecutionError.Code` which i set in original error is overridden with class name)? 
- And if so, how can I manage such situation?

**Comment by huysentruitw** [comment]
Coincidence or not, I've just opened [this issue](https://github.com/graphql-dotnet/conventions/issues/119)  30 minutes ago 🙂

**Comment by huysentruitw** [comment]
While writing the unit-tests for this PR https://github.com/graphql-dotnet/conventions/pull/122
I've figured that, without custom error transformation, the level of nesting is the same. So I'm not sure if it'll help anything?

**Comment by tlil** [comment]
@BilyachenkoOY can you comment on whether @huysentruitw PR helps you or not?

**Comment by BilyachenkoOY** [comment]
@tlil, @huysentruitw I checked PR and it is fine for me, since my issue was about errors added with middleware and not about thrown exceptions. And now those errors are preserved as I'd expect.
As for thrown exceptions, now I'll be able to write own transformation to unwrap such errors.

So, thank you for this PR!
