### ISSUE TITLE
Allow to set ExposeExceptions

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#121]
Hi.
Probably, it would be useful to add some method like `WithExposedExceptions(bool)` to allow configuring corresponding option (see [graphql-dotnet.github.io/docs/getting-started/errors](https://graphql-dotnet.github.io/docs/getting-started/errors)).
What do you think about this?

**Comment by tlil** [comment]
Sure, if you want, you could raise a PR against the repo? :-)

**Comment by tlil** [comment]
See PR - thanks! Closing :)
