### ISSUE TITLE
Any way to add custom metadata?

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#125]
Hi again.

Is there any way I can add some metadata values  (like in [GraphQl-dotnet documentation]( https://graphql-dotnet.github.io/docs/getting-started/metadata) using attributes, so I can add custom validation via `IValidationRule` or middleware later during the query execution?

**Comment by tlil** [comment]
Hey @BilyachenkoOY - could you provide a bit more context, please? Do you have a concrete example of what you're trying to do? I'll try to advise on what can be done / how to do it.

**Comment by BilyachenkoOY** [comment]
Sure. Lets say we have a set of abilities (e.g. `CreateOrders`, `ApproveOrders`) and there are bunch of settings in admin. Depending on those settings any particular user can be granted to use any of this abilities (on none of them).
Now I wanna restrict access to some field in my schema depending on abilities, so I'd like to write something like this:
```cs

[AbilityTo(Abilities.ApproveOrders, stopRequest: true)]
public ApprovalResult ApproveOrder(string orderId /*, some other params*/) { return null; }

```
Now if my attributes will add those params to metadata I'd be able to write single validation rule which validates all such fields using provided metadata and prevents any execution.

**Comment by tlil** [comment]
I wouldn't use a ValidationRule for something dynamic like that. That's exactly what I introduced ExecutionFilterAttributes for. Have you had a look at, for instance, https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Extensions/ChaosAttribute.cs? Would you be able to achieve what you want with an ExecutionFilterAttribute, you think?

**Comment by BilyachenkoOY** [comment]
Yes I saw it. It seems fine except the fact that throwing exception inside `ExecutionFilter`  doesn't stop parallel fields execution, only prevents current.  In the following dummy example I don't want `createOrder` be executed if login is failed:
```
mutation LoginAndCreateOrder {
   login(argumentsHere) {
       token
   }
   createOrder(argumentHere) {
      id
   }
}
```
But if you insist to use execution filter attributes we can adjust our logic, but it will be not elegant solution as with metadata and validation rules / middlewares.

**Comment by vladyslav-didkivskyi** [comment]
Hi,

The same question.
I working on admin part of a website where queries and mutations mustn't be usable for guests.
I use middleware to disable all requests from anonymous users but I need a few queries and mutations on the login page for which I would like to use my custom `[AllowAnonymous]` attribute to mark classes and methods with it.

But I don't see the way how to get the metadata in middleware.
Can you please advise something for it?

**Comment by BilyachenkoOY** [comment]
Not relevant for me anymore
