### ISSUE TITLE
Injecting scoped dependencies

### ISSUE THREAD

**Issue by braudabaugh** [graphql-dotnet/conventions#126]
Certain service objects, like database connections, need to have a lifetime of ServiceLifetime.Scoped so that sharing is limited to a single request.  In order to allow these types of objects to be dependency injected, a new, scoped, dependency injector needs created for each request.  Currently, the injector used to process GraphQL requests is specified when RequestHandler is constructed via the RequestHandlerBuilder.WithDependencyInjector method.  This requires the RequestHandler to be re-constructed with each request in order to inject scoped objects.  In order to avoid this overhead, I would like to propose adding an optional dependencyInjector parameter to the RequestHandler.ProcessRequest method that overrides the injector specified when the RequestHandler was constructed.

I have a PR ready that implements this and will link it to this issue for review.

**Comment by BilyachenkoOY** [comment]
Hello.
Correct me, if I'm wrong, but there should be no difference how and when the dependency injector is constructed if it doesn't holds service instances. For example if you have default Core `IServiceProvider`, it doesn't mean that new scoped/transient services will not be created on the next `GetService` call.

**Comment by braudabaugh** [comment]
The when is definitely different.  In order to use scoped objects, the injector must also be resolved by a scope created at request time.  The code below is basically what I'm using in my app's controller method that handles GraphQL requests. (note: _scopeFactory is an instance of IServiceScopeFactory)

```
           using (var scope = _scopeFactory.CreateScope())
           {
               var customInjector = scope.ServiceProvider.GetService<ICustomInjector>();
               using (var reader = new StreamReader(Request.Body))
               {
                    var query = await reader.ReadToEndAsync();
                    var request = GraphQLWeb.Request.New(query);

                    var result = await _schema.ProcessRequest(request, User, customInjector as IDependencyInjector);
                    return Content(result.Body, "application/json");
               }
           }
```
If you try to use an injector that is not scoped, created by the default provider, to inject a scoped service, you will get an exception similar to:
```
InvalidOperationException: Cannot resolve scoped service 'Blah.Blah+Blah' from root provider.
```

**Comment by BilyachenkoOY** [comment]
You are right :)

**Comment by tlil** [comment]
Thanks for the PR - merged. Closing this issue.
