### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by cable729** [graphql-dotnet/conventions#13]
Thanks again for sharing this code @tlil! It would be nice to know what's being worked on in this library, so we can know what is coming up, as well as what we can help with. I don't think a full roadmap is necessary; some brainstorming based on this list would probably be sufficient:

1. What's being worked on now that's not recorded in issues?
1. What needs work?
1. Planned improvements
1. Improvements that are out of scope right now

**Comment by tlil** [comment]
@cable729 - How's it going? I went through my list here today and realised I completely forgot to answer you questions here.

Is there anything in particular that you're interested in knowing?

Some things that are on my list currently:
 (1) Add support for `null` literals (expect that to be added over the next 1-2 weeks)
 (2) Default profilung support
 (3) Conventions for basic data loading
 (4) Improvements to evaluation strategy and general performance improvements
 (5) (Subscriptions, live queries, and the like... Although this is a bit fuzzy at the moment)

**Comment by cable729** [comment]
No particular questions for me. I've actually moved over to the Java world (:open_mouth:) so I haven't been following  graphql-dotnet much. Maybe others who thumb-up'd my comment have questions though?

**Comment by tlil** [comment]
Haha, I won't start a .NET vs Java discussion here ;)

I'll leave this open for a few days to see if any questions come in then...

Cheers

**Comment by cable729** [comment]
Oh, I'm definitely missing .NET already :smile:
