### ISSUE TITLE
GraphQLEngine use TypeResolver instead of ITypeResolver

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#132]
There is `ITypeResolver` interface and it is used by `SchemaConstructor`. But `GraphQLEngine`  [use specific implementation type ](https://github.com/graphql-dotnet/conventions/blob/4a47da243ea7a4868a11b126f7021c16ba94bf3d/src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs#L26): `readonly TypeResolver _typeResolver = new TypeResolver();` and there are no virtual members in the default implementation, so providing your own resolver in the engine constructor will not affect the engine since all calls are non virtual and don't reffer interface.

**Comment by tlil** [comment]
Ah, I see. Fancy raising a pull request? :-)

**Comment by BilyachenkoOY** [comment]
OK, I'll create PR on few days.

**Comment by tlil** [comment]
Fixed in 2.0.3
