### ISSUE TITLE
GraphTypeAdapter constructs output for derived instances

### ISSUE THREAD

**Issue by dmg-hamann** [graphql-dotnet/conventions#137]
I came across a problem where I am using the lazy loading of the entity framework. The entity framework creates proxy classes for lazy loaded properties. Within ConstructOutputType it causes an issue because the derived proxy instance is not recognized as type.

It creates following error message: 

`\"GraphQL.Conventions.Adapters.Types.OutputObjectGraphType1[mytype]\" for \"myressource\" but got: Castle.Proxies.myTypeProxy."`

My suggestion would be to check whether the instance is a subclass of the known type.

**Comment by tlil** [comment]
Thanks - closing the issue since you already raised a PR for it :) Much appreciated
