### ISSUE TITLE
Empty derived interface causes problems

### ISSUE THREAD

**Issue by cable729** [graphql-dotnet/conventions#14]
# Reproduction

I have two interfaces like this:

```
interface IAccount : IEntity<int> { }
interface IEntity<T> { T Id { get; } }
```

Then I have a query that returns something that has an `IAccount`, which causes `IAccount` to be registered.

# Expected

I expect for `IAccount` to have one field: `Id`, and for GraphiQL to not fail.

# Actual

I get this error in GraphiQL:

```
Error: IAccount fields must be an object with field names as keys or a function which returns such an object.
<snip />
```

In the schema returned, `IAccount` it looks like this:

```
{
  "kind": "INTERFACE",
  "name": "IAccount",
  "description": null,
  "fields": [],
  "inputFields": null,
  "interfaces": null,
  "enumValues": null,
  "possibleTypes": [
	{
	  "kind": "OBJECT",
	  "name": "Account",
	  "ofType": null
	}
  ]
}
```

**Comment by tlil** [comment]
Ah, right on! Will get that fixed - thanks for the thorough report! 👍

**Comment by tlil** [comment]
Should be solved in https://github.com/graphql-dotnet/conventions/pull/15
