### ISSUE TITLE
How to use c# extensions just merged?

### ISSUE THREAD

**Issue by MaximS** [graphql-dotnet/conventions#140]
I've added something like this (DataLoaderWithEFCore sample):

```
namespace DataLoaderWithEFCore.GraphApi.Schema
{
    public static class MovieExt
    {
        public static string TitleWithGenre(this Movie movie)
        {
            return movie.Title + "(" + movie.Genre + ")";
        }
    }
}
```

but this new property does not appear in the scheme.

Should I enable the extension explicitly somewhere?

**Comment by tlil** [comment]
Yep, did you do `.WithQueryExtensions(typeof(MovieExt))` ?
See https://github.com/graphql-dotnet/conventions/pull/136 for an example.
