### ISSUE TITLE
Method not found on Mutation

### ISSUE THREAD

**Issue by strpipe** [graphql-dotnet/conventions#142]
Hi,

I have trouble getting mutations to work.
This is my mutation:
```
[Description("The root mutation.")]
public class RootMutation
{
     [Description("Creates a new program and returns it.")]
     public ProgramType CreateProgram()
     {
          return new PogramType();
      }
}
```
It is registed on the RequestHandler and shows up in the shema, however, when I wan to execute the mutation with this query:
```
mutation {
  createProgram{
    name
  }
}
```
I end up with this error:
```
{
  "data": {
    "createProgram": null
  },
  "errors": [
    {
      "message": "Method not found: 'System.Collections.Generic.IEnumerable`1<!!0> GraphQL.EnumerableExtensions.Map(System.Collections.IEnumerable, System.Func`2<System.Object,!!0>)'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createProgram"
      ],
      "extensions": {
        "code": "MISSING_METHOD"
      }
    }
  ]
}
```

Am I missing something obvious? Thank you.

**Comment by tlil** [comment]
What does `ProgramType` look like?

**Comment by strpipe** [comment]
Thank you, the ProgramType looks like this:

```
    [Name("program")]
    [Description("TODO add description")]
    public class ProgramType
    {
        private Program _program;

        public ProgramType(Program program)
        {
            _program = program;
        }

        [Description("The name of the program.")]
        public string Name
        {
            get { return _program.Name; }
        }
    }
```

**Comment by strpipe** [comment]
I have found queries also not to work anymore. It seems to be an issue with the data type.

**Comment by tlil** [comment]
Can you push a branch with a reproducible sample?

**Comment by dmg-hamann** [comment]
`     public ProgramType CreateProgram()
     {
          return new PogramType();
      }`

There you call a parameterless constructor but your ProgramType needs a Program as a parameter otherwise this will be null and it can't return a name. Maybe that is the issue.

**Comment by strpipe** [comment]
No, I am sorry. I even modified the snippets to not leak some details, which might even have removed important details that might cause the problems.

All my queries do not work anymore and currently have not tested the endpoint. I will look into this. Thank you for your answers.

**Comment by BilyachenkoOY** [comment]
@strpipe 
The exception message looks like in #111 . What versions of GraphQL and GraphQL.Conventions are installed?

**Comment by strpipe** [comment]
Thank you @BilyachenkoOY  
GraphQL v2.4.0 and GrapihQL.Conventions 2.0.1 are installed.

**Comment by strpipe** [comment]
Thank you for helping out, updating GraphQL.Conventions to 2.0.4 solved the problem.

**Comment by tlil** [comment]
Ah, cool :-) Glad to hear
