### ISSUE TITLE
Add a runnable sample

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/conventions#152]
it would be nice to have a sample project in the solution that is runnable.

perhaps based on https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.StarWars

happy to attempt a PR if this is something u think is valuable

**Comment by tlil** [comment]
Are you not able to run any of these?

https://github.com/graphql-dotnet/conventions/tree/master/samples

Feel free to raise a PR with another sample if you feel that is needed though. :-)

**Comment by SimonCropp** [comment]
sigh. dont know how i missed that. so sorry
