### ISSUE TITLE
Multi enumeration bugs

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/conventions#153]
there are several places where enumeable are enumerated multiple time. eg:

            if (listeners != null && listeners.Any())
            {
                foreach (var listener in listeners)
                    configuration.Listeners.Add(listener);
            }

this can result in results being lost if the enumeable  works in a "once only" way.

let me know if u want a PR that fixes them

**Comment by tlil** [comment]
Hey @SimonCropp , sorry this completely slipped my mind. Happy for a PR if you wanted to raise one? :-)
