### ISSUE TITLE
Double Schema initialization

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#154]
Currently making `GraphQLEngine` singleton doesn't guarantee that Schema will not be initialized twice and this leads to strange resolvers duplication in tracing info.
Steps to reproduce:
1. Create and initialize singleton engine (you can even call `BuildSchema`)
2. Create several executors (e.g. first page is loaded and creates multiple requests to GraphQL API) and execute queries in parallel with enabled profiling
3. Enrich results with Apollo tracing
As a result, there are multiple resolvers in tracing info:
![Capture](https://user-images.githubusercontent.com/10833213/54741889-73366d80-4bc8-11e9-9bf4-f61028aa152e.PNG)

Seems that this is because of `Schema.Initialize()` is being called first only on execution and can be solved by putting `lock` on first execution in `GraphQLEngine.Execute`.

**Comment by tlil** [comment]
Added https://github.com/graphql-dotnet/conventions/commit/a3a0026ffd28b143fa17622b4ee09cf7f88aa0c9 to caution against concurrent calls to `BuildSchema()` - can you ping me back if that doesn't resolve the issue? Cheers!
