### ISSUE TITLE
When to use GraphQL Engine over RequestHandler?

### ISSUE THREAD

**Issue by strpipe** [graphql-dotnet/conventions#155]
Hello, 

how do I choose between these two? Do these two classes solve different problems? It seems that the request handler cannot suppress stack traces, so I will probably have to take the former.

Thank you.

**Comment by tlil** [comment]
The latter is just a convenience class wrapping around some of the behaviours offered by the engine. So really depends on your use case and whether RH does what you need it to do :-)
