### ISSUE TITLE
Upload and Download files

### ISSUE THREAD

**Issue by hnviradiya** [graphql-dotnet/conventions#156]
there are some solutions given for graphql .net but I am unable to make it work to upload and download files using conventions.

Can there be an example of this if possible (using conventions)

**Comment by BilyachenkoOY** [comment]
As far as I know, files are out of GraphQL specification and should be implemented next to GraphQL handler. We came up with the following solution:
- Create middleware to serve files by URL (you can use filepath, filename, ID etc.) and return those URLs from GraphQL queries
- As for upload, we add files into HTTP headers (like in multipart/form-data) and only passing their names (paths/IDs) as mutation's fields arguments. Later we can (pre)process those streams from `HttpContext` in controller (for example) to put `Stream`s into `UserContext` where they can be accessed by their names (paths/IDs) from the mutation methods.

**Comment by hnviradiya** [comment]
Great. Thanks.
