### ISSUE TITLE
SchemaPrinter customization

### ISSUE THREAD

**Issue by johannroth** [graphql-dotnet/conventions#157]
Hello,

I currently have the problem, that printing the schema via GraphQLEngine.Describe() includes GUID as type in fields but misses the definition of the scalar GUID. This clashes with graphql client libraries (JavaScript) that I am using (we use the more readable printed schema instead of introspection partly to simplify tracking changes in schema).

The GraphQLEngine manually removes custome scalars like GUID from the schema on initialization of the schema printer:
```
        public GraphQLEngine BuildSchema(params System.Type[] types)
        {
            if (_schema == null)
            {
                if (types.Length > 0)
                {
                    _schemaTypes.AddRange(types);
                }
                _schema = _constructor.Build(_schemaTypes.ToArray());
                _schemaPrinter = new SchemaPrinter(
                    _schema,
                    new SchemaPrinterOptions
                    {
                        CustomScalars = new List<string> { TypeNames.Url, TypeNames.Uri, TypeNames.TimeSpan, TypeNames.Guid },
                        IncludeDescriptions = _includeFieldDescriptions,
                        IncludeDeprecationReasons = _includeFieldDeprecationReasons,
                    }
                );
            }
            return this;
        }
```
As the GraphQLEngine give access to neither the generated ISchema nor the SchemaPrinter, my workaround was to manually replicate the generation of the schema using the SchemaConstructor and generate my own schema and schema printer with my custom configuration.

My questions:

1. Why are custom scalars explicitly removed from the printed schema?
2. Could the GraphQLEngine provide access to the generated schema or the printer?

Thanks!
Johann

**Comment by tlil** [comment]
Added an option to `Describe()` so that you can instantiate your own printer based on the schema: https://github.com/graphql-dotnet/conventions/commit/1c91605fda8409fec89aaa2a4cbd4af2871bc146
