### ISSUE TITLE
Submodule vs nuget dependency

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#16]
Why is this library adding graphql-dotnet as a git submodule rather than having a nuget dependency on it?

**Comment by tlil** [comment]
We've used a derived branch of graphql-dotnet internally so far and have generally been a few commits off from what's officially in the public repo. To avoid that being a blocker on our development and deployment process, and to remove some of the friction in development, we've set it up as a submodule instead. This might well change in the future though. For now, this has been a simplification to save time.

**Comment by huysentruitw** [comment]
Thanks for the clarification.
