### ISSUE TITLE
Must be a reference type (NonNull<T>)

### ISSUE THREAD

**Issue by shoe-diamente** [graphql-dotnet/conventions#161]
Is it possible to specify a `NonNull<Id>` in some way? If I try `NonNull<Id>` or `NonNull<int>` it throws:

> The type 'Id' must be a reference type in order to use it as parameter 'T' in the generic type or method 'NonNull<T>'

**Comment by tlil** [comment]
`Id` is a struct, thus a non-nullable type. No need to wrap it. To make it nullable, use `Id?`.

**Comment by shoe-diamente** [comment]
I'm dumb. Sorry.
