### ISSUE TITLE
mix use of conventions and graphtype first approach

### ISSUE THREAD

**Issue by aeyaey** [graphql-dotnet/conventions#163]
We use the classic graph-type first schema approach in our graphql-dotnet implementation until now. I like the concept of attribute based markup schema generation of conventions, but can't figure out how to mix the two approaches in one setup. Is it possible and what is the limitations?

**Comment by blissi** [comment]
I am interested in that, too...currently I'm trying to get GraphQL.EntityFramework running for some resolvers, but that doesn't seem to mix with this library.

**Comment by tlil** [comment]
Yes, take a look at [DynamicConstructionTests.cs](https://github.com/graphql-dotnet/conventions/blob/master/test/GraphQL.Conventions.Tests/Adapters/Engine/DynamicConstructionTests.cs) :-)
