### ISSUE TITLE
GraphQLEngine - make _documentExecutor passable through the constructor 

### ISSUE THREAD

**Issue by K-Pavlov** [graphql-dotnet/conventions#165]
Currently the IDocumentExecuter in GrapQLEngine is a readonly field which is set to a concrete type:
`private readonly IDocumentExecuter _documentExecutor = new GraphQL.DocumentExecuter();`
This is not ideal as DocumentExecuter gives us the ability to control the IExecutionStrategy:
`protected virtual IExecutionStrategy SelectExecutionStrategy(ExecutionContext context)`
which is currently not possible when using the GrapQLEngine

**Comment by tlil** [comment]
👍 Merged. Thanks!
