### ISSUE TITLE
The use of FetchData

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#17]
What's the idea behind the `FetchData` method on the `IDataLoaderContextProvider` interface?

**Comment by tlil** [comment]
Work in progress, but the idea was to extend it so that the context could be automatically linked in for use with a data loader:

![image](https://cloud.githubusercontent.com/assets/5948145/23836044/84a09ed8-0769-11e7-892e-6892ca053fec.png)

Where `Get<T>(Id id)` would enqueue those requests and `FetchData()` would group, batch and resolve any incomplete tasks; for example, with an example schema like:

![image](https://cloud.githubusercontent.com/assets/5948145/23836051/a11c7bc2-0769-11e7-8250-99cebffca5e2.png)

It's obviously incomplete, but I will hopefully get back to working on that soon. Not had much time to devote to the project over the past few weeks.

Will add some documentation as soon as I have it in a workable state.

**Comment by huysentruitw** [comment]
Re-checking this data loader thing, and I currently have something setup. But shouldn't `FetchData` be called on the `AfterExecutionAsync` instead of `BeforeExecutionAwaitedAsync`, see [source](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Adapters/Engine/Listeners/DataLoader/DataLoaderListener.cs#L9). I have an implementation that collects the tasks to be resolved, but then I would need the after execution event to actually batch query the data and resolve the collected tasks.

**Comment by trbngr** [comment]
Is there an example of this working with DataLoader or anything else?

**Comment by tlil** [comment]
@trbngr: Not a complete example yet AFAIK. I've got some updates coming soon and will try to include a complete example then.

@huysentruitw might have an example though...?

**Comment by huysentruitw** [comment]
Yes, we're using this in combination with Autofac and my self-brew dataloader implementation [YADI](https://github.com/huysentruitw/yadi) which is also available on NuGet.

In short: a dataloader collects field-resolver requests and resolves them all at once in the FetchData method. This way you can combine f.e. 10 separate requests into one SQL query. I'll try to explain with a car/driver example:

    [ImplementViewer(OperationType.Query)]
    public sealed class Query
    {
         public Task<Car[]> Cars([Inject] ICarDataLoader loader, CarOrder order = CarOrder.None)
            => loader.LoadCars(order);
    }

    public class Car
    {
        private readonly CarEntity _entity;

        // We are using Automapper for this, but for simplicity I'm leaving this out by passing the entity model to the constructor
        public Car(CarEntity entity)
        {
            _entity = entity;
        }

        public Guid Id => _entity.Id;
        public string Brand => _entity.Brand;
        public string Model => _entity.Model;

        public Task<Driver> Driver([Inject] IDriverDataLoader loader)
            => loader.LoadDriver(_entity.DriverId);
    }

    public class Driver
    {
        private readonly DriverEntity _entity;
    
        public Driver(DriverEntity entity)
        {
            _entity = entity;
        }

        public Guid Id => _entity.Id;
        public string Name => _entity.Name;
    }

Let's say you query all cars including their driver and there are 100 cars in the list. Without dataloader, you would have to query the driver for each car by the driverId, which would result in 101 database queries (1 to get the list of cars, 100 to get each driver separately).

With a dataloader, the amount of queries will be reduced to two: 1 to get the list of cars, 1 to get the 100 drivers. This works because `loader.LoadXxx` returns a `Task` promise that will be resolved later (when the `FetchData` method is called), a loader also collects all keys that we need to query, in the case of `LoadDriver` the loader will collect a list of driver Ids. When the loader actually fetches the data, we load all drivers at once: `SELECT * FROM Drivers WHERE Id IN (<list of 100 driverIds>)`, after that the loader returns a dictionary where the key is the driver Id and the value is the `Driver` instance. YADI uses the key in the dictionary to resolve the `Task` promises it returned earlier with the correct value.

With YADI and EntityFramework, the dataloaders would look like this:

    public class CarDataLoader
    {
        private readonly DataLoaderContext _loaderContext;
        private readonly MyDbContext _dataContext;

        public CarDataLoader(DataLoaderContext loaderContext, MyDbContext dataContext)
        {
            _loaderContext = loaderContext;
            _dataContext = dataContext;
        }

        public Task<Car[]> LoadCars(CarOrder order)
            => _loaderContext.GetOrCreateLoader<CarOrder, Car[]>(FetchCars).LoadAsync(order).DefaultToEmptyArrayAsync();

        private async Task<IReadOnlyDictionary<CarOrder, Car[]>> FetchCars(IEnumerable<CarOrder> orderings, CancellationToken token)
        {
            // Since there is no pagination or filtering required, we can do the sorting in memory
            var cars = _mapper.Map<Car[]>(await _dataContext.Cars
                .AsNoTracking()
                .ToArrayAsync(token)
                .Select(x => new Car(x))
                .ConfigureAwait(false));

            return orderings.ToDictionary(ordering => ordering, ordering =>
            {
                switch (ordering)
                {
                    case CarOrder.BrandAsc: return cars.OrderBy(x => x.Brand).ToArray();
                    case CarOrder.BrandDesc: return cars.OrderByDescending(x => x.Brand).ToArray();
                }

                return cars;
            });
        }
    }

    public class DriverDataLoader
    {
        private readonly DataLoaderContext _loaderContext;
        private readonly MyDbContext _dataContext;

        public DriverDataLoader(DataLoaderContext loaderContext, MyDbContext dataContext)
        {
            _loaderContext = loaderContext;
            _dataContext = dataContext;
        }

        // This method returns a promise for each call to the car.Driver field resolver
        public Task<Driver> LoadDriver(Guid driverId)
            => _loaderContext.GetOrCreateLoader<Guid, Driver>(FetchDriver).LoadAsync(driverId);

        // This method will be called once during the fetch call
        private async Task<IReadOnlyDictionary<Guid, Driver>> FetchDriver(IEnumerable<Guid> ids, CancellationToken token)
            => await _dataContext.Drivers
                .AsNoTracking()
                .Where(x => ids.Contains(x.Id))
                .ToDictionaryAsync(x => x.Id, x => new Driver(x), token)
                .ConfigureAwait(false);
    }

Each request has it's own `DataLoaderContext` and this is managed by Autofac in our project.

The user-context looks like this:

    public sealed class UserContext : IUserContext, IDataLoaderContextProvider
    {
        private readonly DataLoaderContext _dataLoaderContext;

        public UserContext(DataLoaderContext dataLoaderContext)
        {
            _dataLoaderContext = dataLoaderContext ?? throw new ArgumentNullException(nameof(dataLoaderContext));
        }

        public Task FetchData(CancellationToken token) => _dataLoaderContext.Complete(token);
    }

One last warning is that we're dealing with complex async stuff here and it's very easy to break the task completion chain and to dead-lock your code 🙂 That's also the reason why we're using `.ConfigureAwait(false)` everywhere in our API code as without it we get into a deadlock when certain parts get offloaded to a separate thread by the .NET framework. I think the original [DataLoader for DotNet library](https://github.com/dlukez/dataloader-dotnet) has a better way for dealing with this but it was too limited for our situation.

**Comment by trbngr** [comment]
Thanks so much for detailed reply. I will jump back into this soon.

**Comment by trbngr** [comment]
So it seems I need this to fire `AfterExecutionAsync` instead of `BeforeExecutionAsync` too.

**Comment by huysentruitw** [comment]
Nope, that's a beginner mistake (I already PR'd that earlier, see above, but we had to revert that).

It is now fired on `BeforeExecutionAwaitedAsync`, which is AFTER calling Execute, but BEFORE the task returned by Execute is awaited. So this really is the correct place to start fetching.

As soon as you'd call await on the Execute task, the whole thing would dead-lock because the dataloader task promises would never resolve, and you would be waiting forever. As a result `AfterExecutionAsync` would never be reached.

**Comment by tlil** [comment]
Exactly – thanks for your detailed explanations @huysentruitw – I've been rather busy on my end recently.

**Comment by trbngr** [comment]
I'm not around the project currently, so I can't post an example. But basically, `IDataLoaderContextProvider.FetchData` is being called before I even have a chance to queue a task in a `IDataLoader`. I'm having a hard time explaining. ;)

I just thought of a possible reason though....Does this fork of GQL-dotnet do something else than the official version? Because I have a package reference to the official release. I hope that's it. haha

**Comment by huysentruitw** [comment]
That's because you have an other async/await call between the field and the dataloader, which doesn't work with my implementation. It might work with DataLoader for DotNet though. The Yadi implementation has a while loop that exits when there are no more task promises to resolve, so if you didn't queue one in the first run, you're out of luck. It works in our code because we know this limitation.

If you can post a minimal reproduction of the problem I might be able to point out what the exact problem is.

About your second question, see https://github.com/graphql-dotnet/conventions/issues/16 .

**Comment by tlil** [comment]
@huysentruitw @trbngr FYI, I've started work on https://github.com/graphql-dotnet/conventions/issues/80 to pull out the embedded dependencies on graphql-dotnet and graphql-parser and make them NuGet dependencies instead. That will also allow you to use the latest version of graphql-dotnet (2.#.#, alpha, with different execution strategies).
