### ISSUE TITLE
Problem with default ObjectReflector behaviour

### ISSUE THREAD

**Issue by cs-util** [graphql-dotnet/conventions#170]
I have a problem with the schema generation based on my classes:

Let's say I have an external interface I have no control over, named `SomeExternalInterface` 
And I have a class `MyClass1` that I want to use in the Schema that implements this `SomeExternalInterface`.
Since I cant add the `[Ignore]` annotation to the external `SomeExternalInterface` the complete scheme generation breaks if e.g. a `Dictionary<string, object>` is used as the return type of a property or method and I could not find any way in the code how to exclude these interface properties and methods from the schema. 

Here a code example:

```
        public interface SomeExternalInterface {

            string MyName { get; }

            Dictionary<string, object> ShouldNotBeInSchema { get; set; }

            Dictionary<string, object> ShouldNotBeInSchema2();

        }

        public class MyClass1 : SomeExternalInterface {

            public string MyName { get; set; }

            [Ignore]
            public Dictionary<string, object> ShouldNotBeInSchema { get; set; }

            [Ignore]
            public Dictionary<string, object> ShouldNotBeInSchema2() { return null; }

        }

        [Description("This query will kill the complete schema")]
        public async Task<MyClass1> GetMyClass1() {
            return new MyClass1() { MyName = "123" };
        }
```

My best guess from reading the code is that it would make the most sense to modify the `ObjectReflector` and add a `Func<bool> IgnoreCallback` or something similar to allow the developer to insert custom logic based on the specific type and member info

Should I do it this way and create a pull request or is there an easy way to do this that I am not seeing?

**Comment by tlil** [comment]
Closing since this is now tracked in #171  - ta
