### ISSUE TITLE
Any release insights?

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#175]
I'm wondering if/ when you are going to release (publish into NuGet) the new versions? 'cause I'd like to use recent improvements and fixes (ideally including pending PRs).

**Comment by tlil** [comment]
Yep. Hoping to get to that this upcoming weekend. Apologies for the delay.

**Comment by tlil** [comment]
A bit more of a delay, sorry. ETA within the next week.

**Comment by tlil** [comment]
Will look at getting some of the other outstanding PRs included as well.

**Comment by tlil** [comment]
2.2.0 on its way to Nuget now @BilyachenkoOY

**Comment by tlil** [comment]
https://github.com/graphql-dotnet/conventions/releases/tag/v2.2.0
