### ISSUE TITLE
Is it possible to throw multiple errors?

### ISSUE THREAD

**Issue by shoe-diamente** [graphql-dotnet/conventions#176]
The GraphQL spec allows for multiple errors at any given node. How can I throw/return multiple errors?

**Comment by tlil** [comment]
Yes, each resolver can fail separately, and each error will be collated in the `errors` collection as part of the response. E.g., if you have a request for `{ foo bar }` and the resolvers for both `foo` and `bar` throw an exception, the response would be something like `{ "data": {"foo":null,"bar":null}, "errors": [ <error-for-foo>, <error-for-bar> ] }`

**Comment by shoe-diamente** [comment]
I'm therefore inferring that multiple errors per node (e.g. 3 errors on the `foo` node) is not possible nor recommended?

**Comment by tlil** [comment]
Not seen an example of where that's been needed per se. But depending on use case, you could throw an `AggregateException` and deal with it that way.
