### ISSUE TITLE
Types returned by async subscription methods not unwrapped properly

### ISSUE THREAD

**Issue by braudabaugh** [graphql-dotnet/conventions#177]
There are some problems with how the return type is unwrapped when you have a subscription method with the following signature:
```
public async Task<IObservable<FooType>> FooSubscription()
```
When you look at the schema, the return type for the method is specified as FooTypeIObservable instead of FooType.

Also, fragment validation involving the type will cause this error:
```
Fragment "FooFragment" cannot be spread here as objects of type "FooTypeIObservable" can 
never be of type "FooType"
```
These errors do not occur if you remove async from the method as follows:
```
public IObservable<FooType> FooSubscription()
```
This leads me to believe that the logic that unwraps IObservable is not handling the case where it is nested inside Task.

**Comment by tlil** [comment]
Thanks for the PR. Merged.
