### ISSUE TITLE
Discover derived classes

### ISSUE THREAD

**Issue by BilyachenkoOY** [graphql-dotnet/conventions#179]
I'm writing a framework and would like to allow users to override/extend classes which I return from GraphQL fields. For example:

```cs
 public ShippingCostLine GetShippingCost()
 {
    var line = basket.BasketLines.FindServiceLine(SalesLineTypes.ShippingCosts);
    if (line == null)
        return null;

    // ObjectFactory allows to register derived implementation instead of standard one. 
    var model = ObjectFactory.Create<ShippingCostLine>();
    model.Initalize(line, basket);
    return model;
}

//// Somewhere in the user's project
public class ShippingCostLine2 : ShippingCostLine
{
  public string NewField() => "New field value";
}
//
ObjectFactory.Register<ShippingCostLine, ShippingCostLine2>();
TypeRegistry.Add<ShippingCostLine, ShippingCostLine2>();
```

But `ShippingCostLine2` is not discovered, since `ShippingCostLine` line is not an interface. And I don't want to create interfaces for every single model in my framework. So I tried to write attribute which will mark my models as interfaces, but I end up with the following question:
- why `GraphTypeInfo.IsInterfaceType` ([GraphTypeInfo.cs#L39](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Types/Descriptors/GraphTypeInfo.cs#L39)) has private setter? 

If there is no reasonable arguments against it I'd like to make this setter `public`.

**Comment by tlil** [comment]
Mostly because of what you outline above (the fact that interfaces just get derived from `interface` declarations). I'm fine with a PR to change it to a public setter, provided that sufficient test coverage gets added as well.

**Comment by BilyachenkoOY** [comment]
Looks like it has more step stones then just making public setter, but I still want to try to write my framework without extra c# interfaces. So I'll continue digging

**Comment by tlil** [comment]
Where did you get to with this @BilyachenkoOY ? Will close, but feel free to reopen if you ended up doing something along these lines.
