### ISSUE TITLE
Does "WithExposedExceptions" work as expected?

### ISSUE THREAD

**Issue by shoe-diamente** [graphql-dotnet/conventions#181]
I have set:

```
engine.WithExposedExceptions(false);
```

but exceptions from resolvers (that are not `ExecutionError`s) are still exposed. Specifically, a `System.NotSupported` exception is exposed as:

```
{
  "data": ...,
  "errors": [
    {
      "message": "Specified method is not supported.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [...],
      "extensions": {
        "code": "NOT_SUPPORTED"
      }
    }
  ]
}
```

I'm returning the result via:

```
return enging.SerializeResult(result);
```

What am I missing? How can I prevent exceptions that are not `ExecutionError`s from being exposed?

**Comment by tlil** [comment]
The exception will be exposed, but the stacktrace for said exception won't. See `test/Tests/Adapters/Engine/ExposingExceptionsTests.cs` for examples. Hope that helps.

**Comment by shoe-diamente** [comment]
Oh, I see. Is there any way to customise the error in case of unrecognised exceptions or to block them off entirely?

**Comment by sungam3r** [comment]
In graphql-dotnet you can use `ExecutionOptions.UnhandledExceptionDelegate`.

**Comment by tlil** [comment]
You could also create an execution filter and throw a `try-catch` block around the execution handler :) That way you can control it 100%.

**Comment by shoe-diamente** [comment]
@sungam3r Hi thanks, but it doesn't seem possible to set those options in graphql-dotnet/conventions. Am I wrong?

**Comment by shoe-diamente** [comment]
@tlil Neat. I can't seem to find examples of that in the tests. Is that documented anywhere? Where could I see an example?

**Comment by sungam3r** [comment]
> it doesn't seem possible to set those options in graphql-dotnet/conventions

I guessed about it. I have not watched the conventions project yet, although I can roughly imagine what it is. graphql-dotnet gradually evolves and new features appear in it, the reflection of which should somehow appear in consuming projects.

**Comment by tlil** [comment]
> @tlil Neat. I can't seem to find examples of that in the tests. Is that documented anywhere? Where could I see an example?

Take a look at `ChaosAttribute.cs`, @shoe-diamente  :-)

**Comment by shoe-diamente** [comment]
@tlil In that example should then attach `[ChaosMetaData]` to every field, or...?

**Comment by tlil** [comment]
If you mark it as `IDefaultAttribute`, it will be on by default :)

**Comment by shoe-diamente** [comment]
I've tried with:

```
    public class ChaosAttribute : ExecutionFilterAttributeBase
    {
        public override Task<object> Execute(IResolutionContext context, FieldResolutionDelegate next)
        {
            throw new Exception("WWWWW");
            return next(context);
        }
    }

    public class ChaosMetaDataAttribute : MetaDataAttributeBase, IDefaultAttribute
    {
        public override void MapField(GraphFieldInfo fieldInfo, MemberInfo memberInfo)
        {
            fieldInfo.ExecutionFilters.Add(new ChaosAttribute());
        }
    }
```

but unless I manually add it via `[ChaosMetaData]`, it won't throw exceptions anywhere. I'm missing something.

Do I have to register it somewhere? Can I inject services with the native .NET Core dependency injection system?

**Comment by shoe-diamente** [comment]
It doesn't pick it up because [the method](https://github.com/graphql-dotnet/conventions/blob/c967849614f4a0e5c08a9a2995d5830af344680a/src/GraphQL.Conventions/Attributes/Collectors/AttributeCollector.cs#L80-L94) that discovers them only discovers them in the assembly of the library. There doesn't seem to be a way to specify a different assembly.

**Comment by shoe-diamente** [comment]
I tried with: 
```
var result = await _engine
                .WithExposedExceptions(false)
                .WithAttributesFromAssembly<Graph.ErrorsGuardMetaDataAttribute>()
                .NewExecutor()
                .WithUserContext(userContext)
                .WithDependencyInjector(_injector)
                .WithRequest(requestBody)
                .WithCancellationToken(cancellationToken)
                .Execute();
```

where `Graph.ErrorsGuardMetaDataAttribute` is:

```
    public class ErrorsGuardMetaDataAttribute : MetaDataAttributeBase, IDefaultAttribute
    {
        public override void MapField(GraphFieldInfo fieldInfo, MemberInfo memberInfo)
        {
            fieldInfo.ExecutionFilters.Add(new ErrorsGuardAttribute());
        }
    }
```

Then following the code in this repository I tried to simulate the "search of default attributes" with that method with:

```
            var assembly = typeof(Graph.ErrorsGuardMetaDataAttribute).GetTypeInfo().Assembly;
            var defaultAttributes = assembly
                .GetTypes()
                .Where(type => IsDefaultAttribute(type) && IsTAttribute(type))
                .ToArray();
```

and:

```
        private bool IsDefaultAttribute(Type type)
        {
            return type.GetTypeInfo()
                .GetInterfaces()
                .Any(iface => iface == typeof(IDefaultAttribute));
        }

        private bool IsTAttribute(Type type)
        {
            return type.GetTypeInfo()
                .GetInterfaces()
                .Any(iface => iface == typeof(IMetaDataAttribute));
        }
```
and the array contains 1 element: `Graph.ErrorsGuardMetaDataAttribute`. Which implies that that metadata attribute is correctly found.

But when I try to run a query nothing of `Graph.ErrorsGuardMetaDataAttribute` nor `ErrorsGuardAttribute` gets executed and exceptions other than `AppError` go through.

What am I doing wrong?

**Comment by shoe-diamente** [comment]
Even debugging the engine I get:
![Screen Shot 2019-11-15 at 17 02 02](https://user-images.githubusercontent.com/40760781/68957167-c0a3c280-07c9-11ea-905b-ed430e34e965.png)

And as you can see the `ErrorsGuardMetaDataAttribute` gets correctly registered as a default attribute. But it doesn't actually get executed ever.

**Comment by tlil** [comment]
I missed this response, sorry. If you're still struggling to get it working, please re-open with a repro case that I can look at.
