### ISSUE TITLE
ICollection model properties

### ISSUE THREAD

**Issue by rkotenko** [graphql-dotnet/conventions#182]
I have been using the DataLoaderEFCore sample to get Conventions working with my project.  I am not using a dataloader (yet) or Core though, so I mostly am using the Startup.cs portion as well as general query construction.  I have standard EF models, most of which contain collections referencing other models (these were reverse-engineered from an existing database).  Here is a truncated version of our Application Model:

```csharp
public partial class Application : BaseModel
    {        
        public int id { get; set; }
        public string appName { get; set; }
        public string email { get; set; }
        public ICollection<ItemCategory> ItemCategories { get; set; }
      
        public Application()
        {
            ItemCategories = new HashSet<ItemCategory>();
        }
```

I have a query which returns an application by name.  I am testing this out using GraphiQL.  I can get the scalar properties for an Application fine.  The schema documentation for the ```application``` query shows the fields and GraphiQL autocomplete works.  But the itemCategories field is listed

```javascript
itemCategories: ItemCategoryICollection
```

and it contains no fields. This is also shown as a GraphiQL error in the console

```
Uncaught Error: Type ItemCategoryICollection must define one or more fields.
```
 and I cannot query the itemCategories property at all.  Seems like the collection field is not being recognized as a collection of discreet objects and instead is just being processed as a flat property.

How do I use Conventions to properly handle these fields?

Thanks.

**Comment by rkotenko** [comment]
If anyone has any insight, I would greatly appreciate it.  From what I can tell, since the field is declared as an ICollection, the element type can only be found by looking at ```GetGenericArguments```, but Conventions only calls ```DeriveFields``` for it.  And, of course, it does not find any fields because it is a collection and has no fields.

Again, these are standard EF 6 entity models created programmatically by Visual Studio's reverse-engineering with numerous relationships between classes; I have many collections connecting between my models and really need the API to make these collections available.

 I was able to implement this with standard graphql-dotnet and these fields were all recognized and properly added to the schema when I created and registered types in Startup.  I was under the impression that Conventions would eliminate the need to do this sort of scaffolding though.

**Comment by tlil** [comment]
You want `ItemCategories` to map into a GraphQL type of `[ItemCategory]`, correct? If so, I'm afraid the library only supports `T[]`, `IEnumerable<T>`, `IList<T>` and `List<T>` at the moment. It's not been made more generic than that, unfortunately. See below:

![image](https://user-images.githubusercontent.com/5948145/66869834-19e4c000-ef98-11e9-9460-2fbaa1d7f473.png)

**Comment by tlil** [comment]
If you want to raise a PR with support for `ICollection<>`, I'd be more than happy to take a look :)

**Comment by rkotenko** [comment]
Yeah, I can do that.  :-D

**Comment by rkotenko** [comment]
Question though:  I have added it it, but I am not sure how to actually query the parent model so the collections are included.  If I query to get my application along with itemCategories, the categories are just empty arrays.  That is because I was just returning context.Applications, which does not return any related data unless it is explicitly asked.  As I have multiple related collection properties, I want them to be available without having to note them in queries (as I would in standard GraphQL-dotnet).

How do I make the full graph available for Conventions?

If that is not available, I can also look into how that might be accomplished as well

**Comment by K-Pavlov** [comment]
@rkotenko If I understand your question correctly, it is how to register a type without including it in a query; As far as I know all types which are in the Query / Mutation in the Schema or are used somewhere in the classes in the Query / Mutation in the Schema without an [Inject] attribute (with a few exceptions for some Conventions classes) are registered - and nothing else is; If this is not your question could you provide an example of what you want to accomplish

**Comment by rkotenko** [comment]
Alright. This is going to be a bit lengthy.

I have an model, used with Entity, shaped like this:

```csharp
public class App {
    public App() {
        itemCategories = new HashSet<ItemCategory>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public ICollection<ItemCategory> itemCategories { get; set;}
}
```

This is just the standard Entity shape with the ICollection  being a foreign reference to the ```ItemCategory``` model.  The Entity context uses this model to make a DbSet.

Now, from what I *thought* Conventions was for (and here is where we might need to clear up my misconceptions) was wrapping my model classes such that I did not have define explicit graph types for GraphQL-dotnet.  Using just that library, I would need to create a graph type with a ```Field``` for each model property I need for my query.  So I would have a field with a resolve set for getting the itemCategories.  I thought Conventions would alleviate this by creating graph types based on my model shapes.  And it "kinda" does.  If I look at the Schema for my ```Application``` query I can see an array for ```itemCategories``` and I can drill down into that and see the full model for a single ItemCategory.  So it registers the type correctly (with the fix I made to include ICollection as an Enumerable type)

It is not registration, but resolution that is the problem.  And this may just be the way I have my service set up.  My queries are set up to be as simple as possible right now.  No tasks with async...just simple Enumerable returns.

I have my query for ```Applications``` set so it calls service.GetApplications().

GetApplications() simply returns IEnumerable<Application> via entityContext.Applications.

This then sets the resolution source to the DbSet proxy for Applications.  The problem then is when Conventions goes to get ItemCategories.  Because this source was created via Entity, it is lazy loaded; ItemCategories was not requested, so the source for it has 0 elements.  

So I guess it comes down to 2 main questions:

**Do I have to explicitly create types when I have models which reference other models?**  If so, that seems opposite of what I had thought Conventions was for.

**If not, how can I make it so my source will hit the database for field resolution instead of using an in memory collection?**

**Comment by K-Pavlov** [comment]
Yes, I see the problem now; In my opinion exposing database models from your data layer to the GraphQL is just plain wrong from an architectural point of view, which will bring you a lot of headaches, as Entity data might be structured differently, lazy loaded, DynamicProxies are returned, which are not handle by Conventions currently (and probably will never be), etc. Having more models gives you flexibility and a bit more control (as for the current case); 

Do I have to explicitly create types when I have models which reference other models? - No you don't have to, Conventions will do that for you (except for the Inject attribute as mentioned in my previous comment)

If not, how can I make it so my source will hit the database for field resolution instead of using an in memory collection? I would make a ItemCategories method, which forces the join to ItemCategories (but for me this is NOT the right approach at all)

cc @tlil
