### ISSUE TITLE
Type conversion extensibility

### ISSUE THREAD

**Issue by Cherepoc** [graphql-dotnet/conventions#184]
Hi!
How can I extend complex type conversion? I see that there are different Wrappers and Unwrappers, can I extend that functionality? For example, in my GraphQL.net project I can build a schema type from a dictionary that has enum keys, mapping enum values as fields. Also, since there's no Optional type in that library, I created my version of it, which has an object and names of the properties that are present. Turned out to be very useful for my setup, but I can't understand how to implement that pattern in this library. Any suggestions/guides?
Thanks!

**Comment by BilyachenkoOY** [comment]
You can try to create / replace types by applying custom metadata attribute and resolve those field by intercepting calls to them in custom execution filter attribute
