### ISSUE TITLE
Internal LINQ iterator unwrapping

### ISSUE THREAD

**Issue by K-Pavlov** [graphql-dotnet/conventions#188]
In ReflectionExtensions->IsEnumerableGraphType(this TypeInfo type) internal LINQ iterators are not handled (for example - we return a someList.Where(...) from a resolver method) and they are not marked as enumerable graph types

**Comment by K-Pavlov** [comment]
@tlil I have a fix for this too

**Comment by tlil** [comment]
:+1: Thanks!
