### ISSUE TITLE
Register custom scalar types using RequestHandlerBuilder

### ISSUE THREAD

**Issue by yokan87** [graphql-dotnet/conventions#193]
I've seen that I could register my own custom scalar types using the RegisterScalarType function in the GraphQLEngine.
But when I build a RequestHandler  it seems I don't have the possibility to access the GraphQLEngine. Is there a way to register my scalar types when I'm using the RequestHandler?

**Comment by tlil** [comment]
There is not at the moment, no. Happy to accept a PR if you want to take a stab at adding a method for supporting scalar type registration in `RequestHandler.cs`.
