### ISSUE TITLE
"Unexpected type: " error

### ISSUE THREAD

**Issue by K-Pavlov** [graphql-dotnet/conventions#197]
Having this Schema and request
```
    internal class Program
    {
        private static async Task Main(string[] args)
        {
            var res = await GraphQLEngine.New<CoreQuery>()
                 .NewExecutor()
                 .WithQueryString("query { node { id } }")
                 .Execute();

            res.Errors.ToList().ForEach(x => Console.WriteLine(x.ToString()));
        }
    }

    public partial class CoreQuery
    {
        public INode Node()
        {
            return new Test();
        }

        public Test A()
        {
            return null;
        }

        public NonNull<Test> B()
        {
            return null;
        }
    }

    public class Test : INode
    {
        public Id Id => Id.New<Test>(1);
    }
```
Results in a "Unexpected type: " error from GraphQL.NET. This seems very similar to #187, but the same fix breaks a lot of tests;
The contents of the type cache seem wrong to me:
<img width="938" alt="1" src="https://user-images.githubusercontent.com/5255046/68769756-8b626d80-062d-11ea-9280-0c30359a1ed2.PNG">
<img width="938" alt="2" src="https://user-images.githubusercontent.com/5255046/68769758-8b626d80-062d-11ea-8974-366a5abe2c04.PNG">
<img width="941" alt="3" src="https://user-images.githubusercontent.com/5255046/68769759-8bfb0400-062d-11ea-931f-152ee23977ae.PNG">

I am not really sure what the real issue is here and what a suitable fix would be here (and why this comes up after so many working cases)

**Comment by tlil** [comment]
Does changing the following make any difference?

```diff
-public partial class CoreQuery
+public class CoreQuery
```

**Comment by K-Pavlov** [comment]
@tlil No, not really; Switching the name of the A and B methods fixes it though, because of alphabetic sorting and the way a type is chosen (experienced the same behavior with #187)

**Comment by tlil** [comment]
Fix in:
https://github.com/graphql-dotnet/conventions/pull/205

Thanks
