### ISSUE TITLE
Support for ignoring derived interface meant for internal use only

### ISSUE THREAD

**Issue by angelobarandino** [graphql-dotnet/conventions#198]
Hello, I came to a problem where I implemented an interface to my output types where the only role of the interface is to allow me to automatically register type mapping in AutoMapper.

**Example**

```C#
public interface IMap
{
    void Map(Profile profile);
}

public class UserDto : IMap
{
    ...

    public void Map(Profile profile)
    {
        profile.CreateMap(typeof(UserEntity), typeof(UserDto));
    }
}
````

The above example creates the following error:
`IMap fields must be an object with field names as keys or a function which returns such an object.`

I want to stick on the idea on how my DTO's being mapped to entities by the use Reflection.
Is there a way to opt-out or ignore the **IMap** interface from being generated in schema?

I sincerely appreciate the help. Thank you

**Comment by tlil** [comment]
You should be able to decorate the interface with `[Ignore]` :-)
