### ISSUE TITLE
Using Guid's as 'ID' graph type

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#20]
Our models are using `Guid`'s as identifiers and I'm looking for a way to use them with this library.

    public class User
    {
       public Guid Id { get; set; }
    }

One solution is to change the `Guid` to a `string`, but then we need to do the parsing/tostring conversion ourselves and the graphql type of the field ends up being `"String"` instead of `"ID"`, where `"ID"`would be more appropriate.

I tried to register my own `Id` valuetype class by calling `engine.RegisterScalarType<MyId, NonNull<MyIdGraphType>>(TypeNames.Id);` which works for query types, but not for input types on mutations because I can't override the internal `IdGraphType` in the conventions library. This is because `GetPrimitiveType` in `GraphTypeAdapter.cs` always picks the internal `IdGraphType` for "ID" instead of looking for the one I've registered.

We could modify the `GetPrimitiveType` to first look into the registered types, but what bothers me is that this is only a partial solution (and can potentially break existing applications). There is also no support for 2 different `Id` representations, which might also be something that could be supported (f.e. you should be able to use MyId and the conventions Id class in one application, and depending on the type of the mutation or query, the library could select the correct `IdGraphType`). This last part might be a bridge too far.

For now, if we only had a method to override the internal `IdGraphType`, that would be great. I can do the implementation and send a PR, but I would like to know how others would like this to be implemented?

**Comment by huysentruitw** [comment]
I'll open a PR for this after I get the unit tests running (see #30). Meanwhile I'll close this issue.

**Comment by tlil** [comment]
Thanks, just catching up here now. Thanks for the PR.

**Comment by gugoiscardoso** [comment]
Is it possible to use GUIDs now?

**Comment by huysentruitw** [comment]
Yes, it is

**Comment by gugoiscardoso** [comment]
I used Guid in my models, but I had the same error:
ArgumentOutOfRangeException: The type: Guid cannot be coerced effectively to a GraphQL type

**Comment by tecsined** [comment]
Hi @huysentruitw in v0.17.2 Guid is not working. I get this error:
```
//HERE
     var schema = new Schema { Query = new UserResultQuery() };

{System.ArgumentException: The GraphQL type for Field: 'Id' on parent type: 'UserResultType' could not be derived implicitly. 
 ---> System.ArgumentOutOfRangeException: The type: Guid cannot be coerced effectively to a GraphQL type
Parameter name: type
   at GraphQL.TypeExtensions.GetGraphTypeFromType(Type type, Boolean isNullable)
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   --- End of inner exception stack trace ---
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](Expression`1 expression, Boolean nullable, Type type)
  
```
Using this model and this query

 ```
   public class UserResult
    {
        public Guid Id { get; set; }

        public string Username { get; set; }
     
    }
   public class UserResultQuery : ObjectGraphType
    {
        public UserResultQuery()
        {
            Field<UserResultType>(
                "user",
                resolve: context => new UserResult
                {
                    Username = "Denis",
                    Id = new Guid()
                });
        }
    }

```

**Comment by Brandejs** [comment]
Hi,

Today I came across the same problem. Were you able to solve it in any way?

**Comment by huysentruitw** [comment]
That looks like graphql-dotnet, not graphql-conventions.

**Comment by tlil** [comment]
Agreed. Looks like `graphql-dotnet` as @huysentruitw says.

**Comment by ahmadalli** [comment]
@tecsined  I'm facing the same issue. may I ask what is your `UserResultType`?
