### ISSUE TITLE
Expose ExecutionOptions

### ISSUE THREAD

**Issue by blissi** [graphql-dotnet/conventions#201]
It would be great if the library would expose the ExecutionOptions in some way, for example
`_engine.NewExecutor().Configure(options => ...).Execute();`

This would allow us to use other libraries like https://github.com/SimonCropp/GraphQL.Validation:
`_engine.NewExecutor().Configure(options => options.UseFluentValidation()).Execute();`

**Comment by tlil** [comment]
Happy to accept a PR :)
