### ISSUE TITLE
Add enums in schema?

### ISSUE THREAD

**Issue by blissi** [graphql-dotnet/conventions#202]
Hallo,
how can I add an enum to a schema without using it in any GraphQL type or the query?

My use case is as follows:
I have an enum for error codes and I want it to be in the GraphQL schema, because the schema is used to generate TypeScript for Angular. The error codes should also be in the schema.

At the moment I have to do this workaround:
```
    [ImplementViewer(OperationType.Query)]
    internal partial class Query
    {
        [Description("This is just a dummy so that LHErrorCode appears in the GraphQL schema.")]
        public List<LHErrorCode> _ErrorCodes => Enum.GetValues(typeof(LHErrorCode)).Cast<LHErrorCode>().ToList();
    }
```

**Comment by tlil** [comment]
There's no way of doing that, other than through a workaround as per your suggestion above. You could also achieve the same objective dynamically by introducing your own attribute, e.g., `[IncludeEnum(typeof(LHErrorCode))]`, and have that attribute include the enum type definition explicitly.

I don't see a reason for or a consistent way to include that type of functionality in the core library itself to be honest.

HTH.
