### ISSUE TITLE
Fields getting derived in depth even they are ignored

### ISSUE THREAD

**Issue by yokan87** [graphql-dotnet/conventions#203]
Hi,

For example, I've got the following classes:

public class GqlClass
{
    public NonNull<string> Text { get; set; }

    [Ignore]
    public MyClass ToMyClass()
    {
        return new MyClass();
     }
}

public class MyClass
{
    public T SomeGenericMethod<T>()
    {
        return default(T);
    }
}

When I use the GqlClass in a Query class, the startup fails because the field derivation goes through the class "MyClass" and gets an error because of the generic type parameter:

"Cannot create an instance of GraphQL.Conventions.Adapters.Types.OutputObjectGraphType`1[T] because Type.ContainsGenericParameters is true."

**Comment by HakuTheWolfSpirit** [comment]
I'm having the same issue here.
@tlil

**Comment by tlil** [comment]
Thanks for submitting the fix, @jdomnick - merged and will release in a few. Apologies for the delay in getting back to you.
