### ISSUE TITLE
Incompatible with GraphQL.Server Metrics/Instrumentation

### ISSUE THREAD

**Issue by AzureMarker** [graphql-dotnet/conventions#211]
When using GraphQL.Conventions with GraphQL.Server, the following error occurs during the first GraphQL request:
```
GraphQL Error: Unable to cast object of type 'GraphQL.Instrumentation.InstrumentFieldsMiddleware' to type 'GraphQL.Types.IGraphType'.
   at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveTypeFromTypeInfo(Type type)
   at GraphQL.FuncServiceProvider.GetService(Type type) in /_/src/GraphQL/DI/FuncServiceProvider.cs:line 27
   at GraphQL.Types.Schema.System.IServiceProvider.GetService(Type serviceType) in /_/src/GraphQL/Types/Schema.cs:line 107
   at GraphQL.Instrumentation.FieldMiddlewareBuilderExtensions.<>c__DisplayClass3_0.<Use>b__0(ISchema schema, FieldMiddlewareDelegate next) in /_/src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs:line 62
   at GraphQL.Instrumentation.FieldMiddlewareBuilder.Build(FieldMiddlewareDelegate start, ISchema schema) in /_/src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs:line 57
   at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema) in /_/src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs:line 77
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 74
```

[GraphQL.Server.GraphQLOptions.Metrics](https://github.com/graphql-dotnet/server/blob/80bde26b6e0626a01de5b9d87662a0dc24f4187d/src/Core/GraphQLOptions.cs#L19) is enabled by default. This eventually results in a call to [`provider.GetService(middleware)`](https://github.com/graphql-dotnet/graphql-dotnet/blob/07cd4650e6de8bd179581811079cfb9d84bbcccc/src/GraphQL/Instrumentation/FieldMiddlewareBuilderExtensions.cs#L64), where `provider.GetService` is a reference to [`GraphTypeAdapter.DeriveTypeFromTypeInfo`](https://github.com/graphql-dotnet/conventions/blob/84768c601e5b0d226f4f4bf50c403a35fc3d1ed8/src/GraphQL.Conventions/Adapters/GraphTypeAdapter.cs#L44). This function falls back to [`Activator.CreateInstance`](https://github.com/graphql-dotnet/conventions/blob/84768c601e5b0d226f4f4bf50c403a35fc3d1ed8/src/GraphQL.Conventions/Adapters/GraphTypeAdapter.cs#L76), but casts to `IGraphType`. This cast causes the above error.

I think I found a workaround by disabling GraphQL.Server's metrics and manually adding `InstrumentFieldsMiddleware` to the GraphQLEngine via `WithMiddleware`. I'm not sure this is a good/valid fix though. A proper fix might be to remove the cast since the function is only used as the implementation of `GetService`, which only requires `object?` as a return type.

<details><summary><b>Details</b>: <code>ConfigureServices</code> and <code>Configure</code>  methods</summary>
<p>

Here are my `ConfigureServices` and `Configure` methods in `Startup` ([link to file in git repo](https://github.com/forte-music/Forte.NET/blob/2b39f188c72f99703517e8e6a888b74080bdb401/Forte.NET/Startup.cs)):
```c#
        public void ConfigureServices(IServiceCollection services) {
            // Infer the schema using GraphQL.Conventions
            var engine = new GraphQLEngine()
                .WithQuery<Query>()
                .BuildSchema();
            var schema = engine.GetSchema();

            services.AddControllers();
            services.AddSingleton(schema);
            services.AddWebSockets(_ => { });
            services
                .AddGraphQL((options, provider) => {
                    var logger = provider.GetRequiredService<ILogger<Startup>>();
                    options.UnhandledExceptionDelegate = ctx =>
                        logger.LogError(
                            "GraphQL Error: {Error}\n{Stacktrace}",
                            ctx.OriginalException.Message,
                            ctx.OriginalException.StackTrace
                        );
                })
                .AddWebSockets()
                .AddSystemTextJson();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
            if (env.IsDevelopment()) {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
            app.UseWebSockets();
            app.UseGraphQLWebSockets<ISchema>();
            app.UseGraphiQLServer(new GraphiQLOptions { Path = "/graphiql" });
            app.UseGraphQL<ISchema>();
        }
```

</p>
</details>

**Comment by tlil** [comment]
Hey @Mcat12 - apologies for my late response.

Thanks for the above report. It does indeed look like there's a mismatch in return types for [`DeriveTypeFromTypeInfo()`](https://github.com/graphql-dotnet/graphql-dotnet/blob/32e614877cf4a8de6e0b9fc9fb0723498320ee3e/src/GraphQL/DI/FuncServiceProvider.cs#L18). I've attempted a fix on branch [`fix/issue-211`](https://github.com/graphql-dotnet/conventions/compare/fix/issue-211?expand=1) (https://github.com/graphql-dotnet/conventions/pull/212). Could you please take it for a spin and see if the changed signature resolves the issue for you? The [test suite](https://ci.appveyor.com/project/tlil/conventions/builds/37408735) seems unaffected.

**Comment by AzureMarker** [comment]
That does seem to fix the error, although I've since changed to the GraphType approach instead of using this library (I think I ran into some issues with passing through GraphQL Server's context; I tested this fix on a previous revision).

**Comment by tlil** [comment]
No probs. Thanks for checking. 👍

**Comment by tlil** [comment]
If you recall any context around the other issues that you ran into, feel free to elaborate and I can have a look into it.
