### ISSUE TITLE
Access queried fields inside query

### ISSUE THREAD

**Issue by AndreasFurster** [graphql-dotnet/conventions#214]
Take the following query for example;

    [ImplementViewer(OperationType.Query)]
    public class Query
    {
          [Description("Retrieve book by its globally unique ID.")]
          public Task<Book> Book(UserContext context, Id id) => context.Get<Book>(id);
    }

I would like to get a list of the requested fields, so I can create a database query with only those fields (we have very large documents).  

Is this possible?

**Comment by sungam3r** [comment]
It is 100% possible when using GraphQL.NET directly.

**Comment by tlil** [comment]
You should be able to inject `IResolutionContext` into the resolver via DI, and access the `ResolveFieldContext` from there (`FieldContext`).

**Comment by tlil** [comment]
@AndreasFurster - example:

![image](https://user-images.githubusercontent.com/5948145/108912993-4b0be080-7621-11eb-82ea-d342215c2874.png)

Where the method `ResolutionContextField` is an example resolver. :-)

![image](https://user-images.githubusercontent.com/5948145/108913132-7a225200-7621-11eb-8caa-a337f200dd41.png)

**Comment by AndreasFurster** [comment]
That works perfectly! Thanks a lot!
