### ISSUE TITLE
Implicit conversion in IdGraphType adapter

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/conventions#219]
We're in the process of upgrading from 2.x to 4.0.0 and I'm having some trouble in my schema where we have a *nullable* id `Graph.Convention.Id? `. When serializing a response where the id is null we a get: 

```
System.AggregateException: One or more errors occurred. (Unable to decode identifier ''.)
 ---> GraphQL.Conventions.Execution.FieldResolutionException: Unable to decode identifier ''.
 ---> System.ArgumentException: Unable to decode identifier ''.
   at GraphQL.Conventions.Id..ctor(String encodedIdentifier)
   at GraphQL.Conventions.Id.op_Implicit(String encodedIdentifier)
   at GraphQL.Conventions.Adapters.Types.IdGraphType.ParseValue(Object value)
   at GraphQL.Types.IdGraphType.Serialize(Object value) in /_/src/GraphQL/Types/Scalars/IdGraphType.cs:line 70
   at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 471
   --- End of inner exception stack trace ---
```

There seem to be a implicit conversion going on as this failing test illustrate:
```
using GraphQL.Conventions.Adapters.Types;
using Tests.Templates;

namespace Tests.Types
{
    public class IdGraphTypeTests : TestBase
    {
        [Test]
        public void Can_Handle_Null_ParseValues()
        {
            var graphType = new IdGraphType();
            Assert.IsNull(graphType.ParseValue(null));
        }
    }
}
```

Our workaround at the moment is to replace the `IdGraphType`  the following version that does not result in the automatic conversion. 
```
    public class WorkaroundForNotBeingAbleToHaveNullableIds : IdGraphType
    {
        public override object ParseValue(object value)
        {
            if (value == null)
            {
                return null;
            }
            return new Id(value.ToString());
        }
    }
```

I'm not so familiar with the inner workings of the framework so I can't say if this is a bug or if we are somehow using this wrong. What do you recon?

**Comment by tlil** [comment]
From a quick glance at it, it seems like this was introduced in https://github.com/graphql-dotnet/conventions/commit/f02cddaaaaf1bd1951055e096003c58fa2913783. @schabannes any thoughts? :)

**Comment by schabannes** [comment]
Which version of GraphQL.Conventions are you using?
I'm surprised as your implementation in 'WorkaroundForNotBeingAbleToHaveNullableIds' is equivalent to the one in [GraphQL.Conventions.Adapters.Types.IdGraphType](https://github.com/graphql-dotnet/conventions/blob/f02cddaaaaf1bd1951055e096003c58fa2913783/src/GraphQL.Conventions/Adapters/Types/IdGraphType.cs) (v 4.1.0)

**Comment by tlil** [comment]
👍  Looks like a 4.0.0 issue, and that you'd be fine if bumping up to 4.1.0?

**Comment by baluubas** [comment]
> Which version of GraphQL.Conventions are you using?

We're on 4.0.0. 

> I'm surprised as your implementation in 'WorkaroundForNotBeingAbleToHaveNullableIds' is equivalent to the one in [GraphQL.Conventions.Adapters.Types.IdGraphType](https://github.com/graphql-dotnet/conventions/blob/f02cddaaaaf1bd1951055e096003c58fa2913783/src/GraphQL.Conventions/Adapters/Types/IdGraphType.cs) (v 4.1.0)

Yes, I would have thought so too but a decompiler gives me this class (via jetbrains decompiler). Which gave me a hint about the unwanted cast. 

```
  public class IdGraphType : GraphQL.Types.IdGraphType
  {
    public override object ParseValue(object value) => (object) (value != null ? new Id(value.ToString()) : (Id) (string) null);
  }
```

**Comment by tlil** [comment]
>We're on 4.0.0.

Duh 🤦  I was on my phone and confused myself for a sec re version numbers, sorry. I just bumped the package for another update to `4.1.0`, and added your override in `IdGraphType` - can you check if that works for you @baluubas ?

**Update:**

> tlil closed this in 23db689 3 minutes ago

This issue auto-closed based on my previous commit. Feel free to re-open if it doesn't work as expected.

**Comment by baluubas** [comment]
Works as charm on 4.1.0 - thanks 🎉

**Comment by tlil** [comment]
Awesome - thanks for confirming!
