### ISSUE TITLE
Custom attributes for Authentication/Authorization

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/conventions#22]
Hi,

I'm trying to adapt the authentication/authorization sample from the original project: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/learn.md but run in to trouble since I can't find a way to add a FieldMiddlware. I guessing the approach is different with the these conventions and I would be greatful for any tips that could point me in the right direction.

Thank, -Anders

**Comment by baluubas** [comment]
Nevermind. I've found `ExecutionFilterAttributeBase` and that worked like a charm.

**Comment by tlil** [comment]
Glad you found out how to implement it. Sorry, the documentation is pretty poor at the moment. I will try to get some more docs added soon.
