### ISSUE TITLE
Injected dependencies get reflected

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/conventions#24]
Hi,

I have some trouble with building a schema which contain a injected dependency. I'm getting:

`Cannot construct argument 'parameters' of type 'object'; invalid type."`

It seems that reflection is performed on the dependency and in that dependency graph is an `dynamic` parameter called parameters which causes the problem.

The behavior I expected was that `[Inject]`'ed types would be ignored and not reflected upon. Is this a wrong assumption perhaps? If not, let me know what I can do to help.

Btw, a workaround is to make the dependency inherit from IUserContext.

-Anders

**Comment by tlil** [comment]
Yes, sorry there are some bugs in the DI portion of the library that I literally fixed this morning. Will push out a new version in a few hours. :) sorry about that!

**Comment by baluubas** [comment]
Awesome!

**Comment by tlil** [comment]
Merging #25 now, so you should be able to try out v1.1.2 in a few once the AppVeyor build has completed @baluubas. Let me know how you get on with that build.

**Comment by tlil** [comment]
https://www.nuget.org/packages/GraphQL.Conventions/1.1.2

**Comment by baluubas** [comment]
Works like s charm. Nice job.
