### ISSUE TITLE
How to use middleware ? 

### ISSUE THREAD

**Issue by benkhouds** [graphql-dotnet/conventions#241]
I see that in the RequestHandler, there's an WithMiddleware option, but i can't find any example on how to use this :( One more question, is there a way to set a custom deserializer ? 
would be appreciated if you wan provide an example of an auth middleware, thanks

**Comment by tlil** [comment]
It's registering field middleware as it is available in the core repo. Hopefully these docs should help :)

https://graphql-dotnet.github.io/docs/getting-started/field-middleware

**Comment by benkhouds** [comment]
The use case is a little bit unclear, Can i use this for example to override the resolved type ? for example to override the enum values to use PascalCase (my other issue). Or is it the same purpose as an http middleware that can be used to protect queries (check on access token for example ) ? I'm new to this, so this maybe a stupid question, but your help is really appreciated thanks

**Comment by tlil** [comment]
> The use case is a little bit unclear, Can i use this for example to override the resolved type ? for example to override the enum values to use PascalCase (my other issue). Or is it the same purpose as an http middleware that can be used to protect queries (check on access token for example ) ? I'm new to this, so this maybe a stupid question, but your help is really appreciated thanks

See reply in #240 – I'd rather use the `Name` attribute to override the name. Or you can build your own attribute deriving from `MetaDataAttributeBase` – e.g., see how the `NameAttribute` is implemented in this repo ([src](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Attributes/MetaData/NameAttribute.cs)).

The fact that it implements `IDefaultAttribute` by the way, means that it's applied to all types, fields and arguments; hence, the nullable `_name` field of the attribute. It gets set by default based on the derivation logic (unless explicitly overriden with a value); see `MapEnumMember` for how #240 ends up as UPPER_CASE.

**Comment by benkhouds** [comment]
Then what's a real use case for a middleware ? as I asked before can it be used for authentication ? (since i'm creating a mock server, would like to add a middleware to handle that for each request and register it to RequestHandler)

**Comment by tlil** [comment]
Middleware in Convention is a borrowed concept from the parent library. It's supported to pass through, and yes, you can add things like instrumentation (and other things as with middleware used in vanilla ASP.NET). That said, some of these can also be implemented with the conventions base classes like what's described above (the concepts for Conventions were developed just before field middleware was added to the parent library for historic context :-))

Thus, best source around middleware implementation is probably the parent repo, and the issue tracker there, as it's more prevalent and used there.

**Comment by Shane32** [comment]
I’d agree that instrumentation is probably the best use case for GraphQL middleware. Although certainly possible, authentication is best implemented as a validation rule. The main GraphQL.NET repository includes middleware for Apollo Tracing middleware, and the GraphQL.NET Server repository contains a validation rule for authentication. 

Conceptually, middleware executes as each field is executed and for lists may execute many times for the same fields. Whereas validation rules execute prior to any part of the query executing, and are based the input GraphQL query. 

So, validation rules can prevent a query from executing if any part is invalid, and also do not need to process the same field multiple times checking the same requirement. This works perfect for authentication. 

Whereas middleware executed for each executed field, which is necessary to time field executions for instrumentation.

**Comment by Shane32** [comment]
There are also document listeners which are like plugins to the document executer, which can do things like review or alter the validation results or provide configuration prior to execution. Now that the execution pipeline is configurable, documents listeners’ use cases are declining. For one example / use case, the base repo includes a document listener for setting up data loaders.

**Comment by benkhouds** [comment]
Thanks a lot both of you for this clear explanation, i'm closing this. Thanks again
