### ISSUE TITLE
Can't run unit tests

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#30]
I've installed VS2017 but unit tests do not show up in the Test Explorer. I've also tried `dotnet test`, but it complains that the NuGet package `microsoft.testplatform.testhost` is missing. After adding that packages it also doesn't find any test.

This made me wonder how you are running those tests...

**Comment by huysentruitw** [comment]
Ok I finally have it working by removing `dotnet-test-xunit` and adding `Microsoft.TestPlatform.TestHost` + `xunit.runner.visualstudio`. Is this something I can create a PR for, or will it break your setup?

**Comment by tlil** [comment]
I'll put up a PR for this tonight and get that sorted. I've been dev'ing on a Mac and haven't tested it with Visual Studio. Also have to verify that Appveyor got all prerequisites and don't complain. Will CC you on the PR

**Comment by huysentruitw** [comment]
I already have a fork with those package changes and appveyor build (VS2017) and nuget deploy, see https://ci.appveyor.com/project/huysentruitw/conventions

**Comment by tlil** [comment]
Included those changes in https://github.com/graphql-dotnet/conventions/pull/34 - [version 1.2.0](https://github.com/graphql-dotnet/conventions/releases/tag/v1.2.0).

Don't have my Windows machine with me here, so not able to test it right now, but let me know if you experience any problems.

**Comment by gugoiscardoso** [comment]
Is it possible to use GUIDs now?
