### ISSUE TITLE
Optional enums

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#35]
While checking this test: [`Can_Construct_And_Describe_Schema_With_Enums`](https://github.com/graphql-dotnet/conventions/blob/ad6a84c30b2381a9f58d9c906aa73cac3e893313/test/Tests/Adapters/Engine/GraphQLEngineTests.cs#L86), I have a question regarding the fact that:

    public Enum2 Field3(Enum2? arg1, Enum1 arg2, Enum2 arg3 = Enum2.SomeValue2, Enum1? arg4 = Enum1.Option3) => arg3;

translates into:

    field3(arg1: RenamedEnum, arg2: Enum1!, arg3: RenamedEnum! = SOME_VALUE2, arg4: Enum1 = OPTION3): RenamedEnum!

Why is `arg3` required given the fact it has a default value (`Enum2.SomeValue2`) or an other question, if the field is required, what is the purpose of the default value?

I'm asking this question because we try to use an optional enum in our query parameter like `Enum1? myEnum = null`, but `Enum.ToObject` throws an exception 'Value cannot be null' on this line [`argument.DefaultValue = Enum.ToObject(baseType.AsType(), parameterInfo.DefaultValue);`](https://github.com/graphql-dotnet/conventions/blob/ad6a84c30b2381a9f58d9c906aa73cac3e893313/src/GraphQL.Conventions/Types/Resolution/ObjectReflector.cs#L301), so before I try to fix this, I want to understand the default value implementation.

**Comment by tlil** [comment]
@huysentruitw good catch! I think making it optional in this case makes more sense. The NRE should also be fixed. I'll get that sorted. Thanks 👍

**Comment by tlil** [comment]
@huysentruitw FYI: https://github.com/graphql-dotnet/conventions/releases/tag/v1.2.1

A note on the nullable vs non-nullable types: having thought about it, I'd rather have the user being explicit  about it and use a nullable type in C# for those optional arguments. It just makes it more readable and explicit overall IMHO.

I'll close this ticket now, but feel free to comment / re-open if you continue experiencing any problems.

**Comment by huysentruitw** [comment]
@tlil do you still have the same thought about this?

We avoided optional parameters as much as possible since then, but really would like to start using them. My problem is that this code looks a bit crappy:

    public Model FieldA(bool? applyFilter = false)
        => service.GetA(applyFilter ?? false);

since you have to specify the default value twice. In my opinion this would be more readable:

    public Model FieldA(bool applyFilter = false)
        => service.GetA(applyFilter);

For any programmer, in the latter example, it should be quite clear `applyFilter` is optional as that is exactly what it is in C#.

**Comment by tlil** [comment]
@huysentruitw Yeah, I see your point. It would require some re-work, but I can take a look at it and see what I can do. I think it makes sense, but a couple of questions just to make sure I understand your use case fully:

* Why wouldn't you just do something like:

    ```cs
    public Model FieldA(bool? applyFilter)
        => service.GetA(applyFilter ?? false)
    ```

    I.e., provide the default value only once. Is it because you want to have the default value presented in the documentation?

* Would doing something like the following be an alternative (to stay consistent with the typing of the rest of the stack)?

    ```cs
    public Model FieldA([Optional] bool applyFilter = false)
        => service.GetA(applyFilter);
    ```

**Comment by huysentruitw** [comment]
@tlil yes, the default value should be in the documentation. 

I'm not sure about the additional attribute, I would prefer to do it by-convention without attribute. If you're afraid of breaking anything, I don't think you need to because currently the API consumer needs to specify a value even though the back-end specified a default value.

**Comment by tlil** [comment]
Hear hear - I will take a look and get back to you.

**Comment by tlil** [comment]
Hey @huysentruitw - sorry, this has completely slipped my mind. Will take a look.

**Comment by huysentruitw** [comment]
Seems to be fixed, so closing for now :)
