### ISSUE TITLE
Mark a class as input and output type

### ISSUE THREAD

**Issue by huysentruitw** [graphql-dotnet/conventions#40]
Is there a way to have a class marked as both Input and Output Type?

Now we can only use the `[InputType]` attribute or no attribute for marking it as an output. But we have situations where classes need to be Input and Output types.

**Comment by tlil** [comment]
I would advise against using the same class as an input and output type. However, if they overlap and all fields are auto properties, you should be able to derive a class `[InputType] class FooInput : FooOutput { }`. Or something like that... I have not tested that myself though.

**Comment by huysentruitw** [comment]
Deriving is what we currently do, it works but the front-end has to define 2 exact models.

I understand that it's better to have a separate query and mutation model, but we're talking about complex value types used in a Union which is part of a query and could be re-used in a mutation.

Now, we have to create a new union and derive from each type to get its output variant. ~~Switching to a struct would work (because they're in the schema as input and output type) if we didn't have a base-class for our value types (and structs do not support inheritance).~~

**Comment by tlil** [comment]
Kk. Any example code you can post to demonstrate what you're trying to do? Just to make sure I get the whole picture.

**Comment by huysentruitw** [comment]
Sure. First of all, we're dealing with data that describes a dynamic form (user can create his/her own form and choose which fields are on it + the datatype of each field).

We have this mutation:

    [InputType]
    public class AddFormFieldMutation
    {
        public string Name { get; set; }
        public NonNull<DataTypeSet> DataTypeSet { get; set; }
    }

    [InputType]
    public class DataTypeSet
    {
        public DateTimeDataTypeSettings DateTime { get; set; }
        public MoneyDataTypeSettings Money { get; set; }
        public NumberDataTypeSettings Number { get; set; }
        public TextDataTypeSettings Text { get; set; }
    }

This idea is that the front-end only fills in the settings of one datatype, so if the user selects the number type, the settings for that datatype are sent (f.e. pricision, minimum value, maximum value).

At query side we're using a union to return the field settings:

    public class FormField
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DataTypeUnion DataType { get; set; }
    }

    public class DataTypeUnion : Union<
        DateTimeDataTypeSettings,
        MoneyDataTypeSettings,
        NumberDataTypeSettings,
        TextDataTypeSettings>
    {
    }

The front-end requests the settings in all flavors in a single query and then finds out which entry is filled. F.e. if NumberDataTypeSettings if filled, then it knows the number data type is selected and uses the settings.

Each `...Settings` class derives from:

    [InputType]
    [Description("Base class for datatypes")]
    public class DataTypeSettings
    {
    }

So what we want to do is re-use the `...Settings` classes.

The above is currently not possible because our Settings classes are marked as `[InputType]` and it results in a GraphQL schema error. So what we currently do is derive from the input types to get an output type, but then the GraphQL client also has to deal with 2 models holding the same information.

**Comment by huysentruitw** [comment]
I've investigated this a bit more and this even seems to be limited by the GraphQL specification. We can't define the same type as OBJECT_TYPE and INPUT_TYPE at the same time. All we can do is make it a SCALAR (struct), but then we loose the field information in our schema.

So, let us conclude that overriding is the only solution to this problem.

**Comment by tlil** [comment]
Yes, exactly. There are constrains in that respect. Also, in my experience, it makes it cleaner separating input from output when the schema grows.
