### ISSUE TITLE
IValidationRule Support

### ISSUE THREAD

**Issue by harrisse** [graphql-dotnet/conventions#41]
Hello,

I was wondering if there was any way to inject custom validation rules? It looks like `GraphQLExecutor.Execute` always passes null rules to `GraphQLEngine.Execute` [here](https://github.com/graphql-dotnet/conventions/blob/eddd4c1e6293e182007ab56a6e392c45b16a0d91/src/GraphQL.Conventions/Adapters/Engine/GraphQLExecutor.cs#L114) but I figured maybe I was missing something.

Thanks!
Sam

**Comment by tlil** [comment]
Hi @harrisse - yes, it's unintentionally not possible at the moment. I will push a branch to fix that. At the moment it uses the defaults or overrides that with a no-op rule if you choose to disable validation altogether; see [GraphQLEngine#L203-L206](https://github.com/graphql-dotnet/conventions/blob/eddd4c1e6293e182007ab56a6e392c45b16a0d91/src/GraphQL.Conventions/Adapters/Engine/GraphQLEngine.cs#L203-L206).

**Comment by tlil** [comment]
@harrisse - does this work for you: [IGraphQLExecutor.WithValidationRules](https://github.com/graphql-dotnet/conventions/pull/42/files#diff-714b155763e54b3d7478cbfb1ca2f2edR26). Available in [v1.2.5](https://github.com/graphql-dotnet/conventions/releases/tag/v1.2.5).

**Comment by harrisse** [comment]
That's exactly what I was looking for, thanks!

**Comment by tlil** [comment]
Excellent!
