### ISSUE TITLE
Error while updating to 1.2.3 and upper

### ISSUE THREAD

**Issue by Marfusios** [graphql-dotnet/conventions#44]
Hello,

can't update the library to version 1.2.3 and greater.
Exception:
```
Package Newtonsoft.Json 5.0.6 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Newtonsoft.Json 5.0.6 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netcore45 (.NETCore,Version=v4.5)
  - portable-net40+sl4+win8+wp7 (.NETPortable,Version=v0.0,Profile=Profile2)
  - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
One or more packages are incompatible with .NETStandard,Version=v1.6.
Package restore failed. 
```

It seems there is a change in referencing `Newtonsoft.Json` from version '>= 9.0.1' to '>= 5.0.6' and it doesn't work

**Comment by tlil** [comment]
Ah, that's my bad, sorry about that – I will get that updated (we had to downgrade to 5.0.6 due to other dependencies in-house, and are using .NET v4.5, hence why it slipped through). Will push a PR shortly.

**Comment by tlil** [comment]
Should be fixed in v1.2.7: https://github.com/graphql-dotnet/conventions/pull/45. Able to verify for me @Marfusios ?

**Comment by Marfusios** [comment]
Restored, updated, perfect.
Thank you, really quick response!

**Comment by tlil** [comment]
Good stuff 👍  Thanks for reporting!
