### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ordinaryorange** [graphql-dotnet/conventions#53]
@tlil is this project alive ?
Am trying to use it but am hitting a couple of issues. Even tried the src to debug but GraphQL deps all broke.

First issue here [on SO](https://stackoverflow.com/questions/44981794/argument-overloads-for-graphql-field)
Second is that i'm getting a null object from a field when the field returns an interface type. Works if the field return is a concrete type.

**Comment by tlil** [comment]
**Issue no. 1**: Conventions doesn't support method overloads as there are no ways of representing that in GraphQL - you can't have two fields with the same name and different signatures in GraphQL. So if you change to the below, you should be okay:

```cs
public class StarWarsQuery
{
    public IEnumerable<Droid> Droids()
    {
        return droidRepository.GetAllDroids();
    }

    public Droid Droid(string name)
    {
        return droidRepository.GetDroidByName(name);
    }
}

public class Droid
{
    string name { get; set;}
}
```

```graphql
{
   droids{ # note also the lowercase 'd' here
     name
   }
   droid(name:"super droid"){
     name
   }
}
```

**Comment by tlil** [comment]
Can you elaborate on the second issue that you're seeing please?

And to answer your very first question, @ordinaryorange - yep, it's alive :-)

**Comment by ordinaryorange** [comment]
Great to hear the project is alive! I'm surprised about the lack of others here....I think it it a fantastic addition to GraphQL.Net. Without this us .NETers would have a hard time using GraphQL from Facebook.
Thanks for feedback on 1. I'm checking something on that now....
In regard to 2. If I have a Query where all the return types from the fields are interfaces, then I get a null when querying any field. By chance I just discovered that if I add a field that returns a concrete type, which is an implementation of another fields interface, then a call to the interface returning field works! Where as it wont when the other field with the concrete return is not present. So it appears GraphQL needs to be shown all the possible implementations of an interface. Does that sound right ?

**Comment by ordinaryorange** [comment]
i've started another thread for Q1 - #54 to save mixing discussions.

**Comment by tlil** [comment]
It should try to auto-detect those implementations – can you paste a code snippet of the schema and the query?

**Comment by ordinaryorange** [comment]
Digging deeper. My snippet wont fail...grr

**Comment by ordinaryorange** [comment]
Ok narrowed it down. When the interface and the concrete implementation are in the same assembly all works as expected. However when the two are in separate assemblies then the Schema will only contain the interface definition and despite my DI container actually passing back an instantiated concrete instance the query returns null.
An issue somewhere during schema construction ? Or do I have to explicitly show it the possible concrete types ?

**Comment by tlil** [comment]
Gotcha – yes, I'll add a method for adding search assemblies to automatically discover those types. I've already got that in place for attributes and have just forgotten to put in a similar utility for types as a need hasn't presented itself until now :)

Will ping you an update later when I get that updated

**Comment by tlil** [comment]
@ordinaryorange I've pushed a commit with a `TypeRegistry` that allows you to manually register those implementation types: https://github.com/graphql-dotnet/conventions/pull/59/commits/bab6bc8bc87eb10e4c175f269531afef9bd346c9#diff-93a6989a8b2b230a36ecdcaafc5fb12dR11

```cs
TypeRegistry.Add<SomeInterface, Assembly1.SomeImplementation>();
TypeRegistry.Add<SomeInterface, Assembly2.SomeOtherImplementation>();
// ...
```

Types in the same assembly will still auto-register.

Closing this; has pushed out version *1.2.14* to NuGet.
