### ISSUE TITLE
Overloaded fields

### ISSUE THREAD

**Issue by ordinaryorange** [graphql-dotnet/conventions#54]
What I want to do is as per this post [on SO](https://stackoverflow.com/questions/44981794/argument-overloads-for-graphql-field)

@tlil you are correct that GraphQL does not support two fields with the same name. Not sure if this is a limitation with [GraphQL](https://github.com/graphql-dotnet/graphql-dotnet) or [GraphQL](http://graphql.org/) ?
However I see that a field can have multiple arguments.

One possible way (which feels like a bit of a hack) would be to implement a field resolver that inspects the arguments for combinations of null and non null values, and then based on that determine which method overload to call.

Thoughts ?

**Comment by tlil** [comment]
I'm pretty sure it's a limitation of GraphQL itself (i.e., not the C# library).

If you want to separate the logic out to separate resolvers, I would do something like:

```cs
public Droid Droid(string name)
{
    if (string.IsNullOrWhitespace(name))
    {
        return DroidRepository.GetDroidByName(name);
    }
    else
    {
        return DroidRepository.GetDefaultDroid();
    }
}
```

**Note**: The return types of `GetDroidByName` and `GetDefaultDroid` need to be the same obviously, so you can't mix `IEnumerable<Droid>` and `Droid` unless you had the latter case mask as a result of type `Droid[1]`

**Comment by ordinaryorange** [comment]
Did some deep digging on this one, and what I would like to do is outside the current [spec](https://github.com/facebook/graphql)
Conventions and GraphQL (.net) are doing the right thing.

I was thinking about injecting in custom field resolvers into conventions, but doing it externally for now is a simpler woraround.

Ta.

**Comment by tlil** [comment]
👍
