### ISSUE TITLE
No HttpContext with the new default field resolver (WrappedAsyncFieldResolver)

### ISSUE THREAD

**Issue by niklaskallander** [graphql-dotnet/conventions#55]
Hi,

When upgrading to the latest version of conventions, containing the new default field resolver (`WrappedAsyncFieldResolver`) our code stopped working. The resolver uses `Task.Run` which makes the `HttpContext` to get lost.

We can configure our service to use the `Normal` field resolution strategy (which is working fine for us), but I'm curious about the purpose behind `WrappedAsyncFieldResolver`? What benefits does it bring considering it is the new default strategy?

Awesome work, thanks! (:

/Niklas

**Comment by tlil** [comment]
Hi Niklas,

To be honest, the `WrappedAsyncFieldResolver` is a bit of a hack at the moment to get around a conflict with some internal libraries that we have, triggering a deadlock using the normal resolver. And a side-effect is that resolvers get executed sequentially - which obviously isn't great if you've got any expensive resolvers... :-)

That should just be used temporarily until we get to the root of the issue in one of our dependent libraries. In other words, I'd recommend just using the `Normal` field resolution strategy for now (which is the one that's been used in the past).

Will update here on any progress on the matter. And let me know if you run into any other problems.

Cheers :-)

**Comment by niklaskallander** [comment]
Fair enough, thanks for the info!

Just a thought, if it's a temporary hack why make it the default strategy (considering the potential breakage for dependents)?

**Comment by tlil** [comment]
Yeah, that wasn’t supposed to happen - so that was an oversight on my part, sorry. I’ll make that change in the next few days together with some other pending changes.

**Comment by niklaskallander** [comment]
No rush on my behalf, we build from our own mods anyway (to circumvent https://github.com/graphql-dotnet/graphql-dotnet/issues/280), thanks! (:

**Comment by huysentruitw** [comment]
Depending on `HttpContext.Current` is the biggest mistake here 😃

**Comment by tlil** [comment]
🤣  👍

**Comment by niklaskallander** [comment]
@huysentruitw although that is true and all, every now and then, some people (not you, obviously) have to live with decisions made a long time ago (at least for a while longer). 

And to be clear, I'm not complaining about stuff not working, that's fine. We have to live with and suffer for our own sins. We can't expect anyone else to do that for us, can we? 

I'm simply reporting a breaking change that seemed somewhat unintended (+ a work-around, how very nice of me!).

\**sensitive much, indeed** ;-)

**Comment by tlil** [comment]
Yep, that breaking change shouldn't have gotten in there - so that one is on me :) Will get that back in order over the next few days.

**Comment by huysentruitw** [comment]
@niklaskallander didn't want to start a rant. I already have experience with refactoring away `HttpContext.Current` usage in a large enterprise application (because the bloody thing was totally untestable because of that), so I feel your pain. We are now using the conventions library in a new project where it is strictly forbidden to use `HttpContext.Current`, otherwise they'll have to buy me a 🍕 😄

**Comment by tlil** [comment]
@niklaskallander https://github.com/graphql-dotnet/conventions/releases/tag/v1.2.11
