### ISSUE TITLE
How to use the IProvideMetadata API via Convention?

### ISSUE THREAD

**Issue by adebisi-fa** [graphql-dotnet/conventions#57]
Hello,

Thanks for this thorough and brilliant effort to ease off the verboseness of the powerful GraphQL.Net!  It's awesome!!!  

A quick one:

What's the best way to take advantage of the **IProvideMetadata** API of GraphQL.Net?  I'm currently looking into doing Declarative permission on IGraphTypes (**GraphType** and **FieldType**) probably using Attribute and ValidationRule or something.  But none of these are *directly* exposed through the Convention API.  I also considered hooking up a custom **ExecutionFilterAttribute**, but don't know if I'm heading toward the right direction.

Need some help, please?

Thanks.

**Comment by tlil** [comment]
Hi @adebisi-fa,

If you're looking to wrap each resolver with application logic based on associated meta-data, you can extend `MetaDataAttributeBase` and `ExecutionFilterAttributeBase`. Not directly relevant, but I've included an example below. Hopefully, that helps clarify things a bit. Let me know if it doesn't, and I'll try to assist you further:

```cs
public void Main()
{
    var requestHandler = RequestHandler
        .New()
        .WithAttributesFromAssembly<ChaosAttribute>()
        .WithQuery<MyQuery>()
        .Generate();
    
    var result = requestHandler
        .ProcessRequest(Request.New("{ \"query\": \"{ foo bar baz }\" }"), null)
        .Result
        .ExecutionResult;
    
    result.Data.Dump();
    result.Errors.Select(e => Tuple.Create(e.Code, e.Message)).Dump();
}

public class ChaosExecutionFilter : ExecutionFilterAttributeBase
{
    private const int SuccessRate = 50;

    private static readonly Random _random = new Random();

    public override Task<object> Execute(IResolutionContext context, FieldResolutionDelegate next)
    {
        var path = $"{context.FieldInfo.DeclaringType.Name}.{context.FieldInfo.Name}";
        path.Dump();

        if (_random.Next(0, 100) > SuccessRate)
        {
            throw new ChaosException($"Only {SuccessRate} % of requests will succeed.");
        }

        return next(context);
    }
}

class MyQuery
{
    public string Foo => "Foo";

    public string Bar => "Bar";

    public string Baz => "Baz";
}

public class ChaosAttribute : MetaDataAttributeBase, IDefaultAttribute
{
    public override void MapField(GraphFieldInfo entity, MemberInfo memberInfo)
    {
        entity.ExecutionFilters.Add(new ChaosExecutionFilter());
    }
}

class ChaosException : Exception
{
    public ChaosException(string message)
        : base(message)
    {
    }
}
```

This example will essentially cause each of the resolvers to fail and throw an exception 50 % of the time.  You can of course pass down parameters from `ChaosAttribute` to the execution filter and action that information when the resolver gets executed. You can also inspect the associated `GraphFieldInfo` if you need any field-specific information.

**Comment by tlil** [comment]
Closing this; feel free to reopen if that didn't help.
