### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by bentoo** [graphql-dotnet/conventions#58]
We are seeing extremely slow performance 2.3 seconds vs 200 ms for the same functionality with an extremely simple endpoint.

Has anyone else seen similar performance issues?

**Comment by tlil** [comment]
Could you provide some more background please, @bentoo? I'm working on some improvements and are hoping to get an update out early next week; if I spot anything re your issue, I'll try get that in as well.

**Comment by huysentruitw** [comment]
@tlil Could this be because of the default field resolver change you did in #55 ?

**Comment by tlil** [comment]
I don't know; possibly. That's been reverted now though. I've not seen any performance issues myself re this; so waiting for @bentoo to provide some more context :)

You seen anything your end @huysentruitw ?

**Comment by huysentruitw** [comment]
No, I have tested a complex query which takes only 80ms in debug, latest version 1.3.0 and `FieldResolutionStrategy.Normal`, so let's wait :)

**Comment by tlil** [comment]
Cool - thanks for confirming on your end. By the way, pushed out 1.3.1 here now with a fix for `Metrics` - it wasn't thread-safe before.

**Comment by bentoo** [comment]
The new GraphQL library's source in the Visual Studio 2017 format, so I failed to build it from source even after changing version in project files. This is why eventually I had to install the latest version of GraphQL Conventions 1.3.5 from NuGet.

Created a standalone .NET Core application running a Kestrel Server.

The project code is
[graphql-benchmarks-master-fa2e2a4c95bf53a62e1bc22f6c8f0afd75fd6ebd.zip](https://github.com/graphql-dotnet/conventions/files/1242290/graphql-benchmarks-master-fa2e2a4c95bf53a62e1bc22f6c8f0afd75fd6ebd.zip)


The new and old libraries are not compatible in terms of method names etc, so in order to have one project for both libs, the conditional compilation is used (symbol OLD_LIB)

*The Test*
We are benchmarking the performance of rendering 1Mb of JSON data represented as an array or small objects.

3 implementations are compared:
- Older library
- Newest library
- No GraphQL

In all the tests the server was:
- Running locally
- Published/Compiled as a release version
- Launched from outside the debugger, just in console
- Environment: Windows 10, 64bit Pro, 16 Gb RAM, 4 Cores  

GraphQL request:
{code}
POST /graphql HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Cache-Control: no-cache


{
  "query": "query M($size: Int)  
   {
        perf_no_db(
                  input: {
                    size: $size
          })
          {
            result
            id
            firstName
            lastName
            fullName
            userName
            email
            avatar
            gender
            cartId
          }
   }",
   "variables":
   {
        "size": 1000000
   }
}
{code}

Raw request:
{code}
GET /performance?size=1000000&amp;test=JSON_SI_DB_NO_GRAPHQL_NO HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Cache-Control: no-cache

{code}

*Results*

Results measured with the Kestrel diagnostics gave the below output:

||Version||Best Time||Worst Time||
|GraphQL Conventions 1.3.5|250 ms|320 ms|
|GraphQL Conventions 1.0.8|400 ms|600 ms|
|No GraphQL|26 ms|34 ms|
|My GraphQL|35 ms|40 ms|

*Conclusion*
* Both the old and the new versions of GraphQL Conventions demonstrate poor performance
* The new one works faster than the old one by 90%
* Even the new version of GraphQL Conventions works 10x times slower than raw requests

As I reported earlier the major reason for slowness is the complexity of GraphQL which affects the performance of rendering for big collections of objects to response.

MyGraphQL = I commented out the following line of code:

resolveResult.Value =
                    await CompleteValueAsync(context, fieldDefinition.ResolvedType, fields, result).ConfigureAwait(false);


which means that I lose support for being able to return a dynamic list of columns and associations. (which basically means that it is no longer graphql. Some of my queries don't need this feature so I am going to simply add a flag to skip it on those queries).

**Comment by tlil** [comment]
Sorry for the late reply @bentoo – I've been out for a month and just catching up on my emails here now.

On a general note: Some performance penalties are expected as the resolution is dynamic, but I'm sure there are further improvements to be made. I've got some plans for a future fork of this library that will be more geared towards performance, but haven't had time to start on that yet.

In the meantime, I'll take a look if there are any quick wins / low-hanging fruit that I can address.

**Comment by tlil** [comment]
As improved performance will be something that is continuously worked on and in incremental steps, I will close out this issue. If you've identified specific performance bottlenecks however, feel free to raise an issue, or better still one or more PRs to improve/remove said bottlenecks
