### ISSUE TITLE
Dynamic Registration of IMutation<TInput,TOutput>

### ISSUE THREAD

**Issue by JJLost** [graphql-dotnet/conventions#64]
Taking a look at the [GraphQL Relay Project ](https://github.com/graphql-dotnet/relay) i really liked the use of the [Mutation Payload](https://github.com/graphql-dotnet/relay#mutationpayloadgraphtypetsource-tout-mutationpayloadgraphtypetsource-mutationpayloadgraphtype)

I was looking through the project code looking for a way to easily register something like 
`public interface IMutation<TInput,TOutput>
{
   Task<TResult> Mutate(TInput input)
}`

Some kind of List of IMutation's would then get registered as endpoints by the class name that implements IMutation.  I initially tried to do something like the dynamic schema show in your [Tests](https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Adapters/Engine/DynamicConstructionTests.cs) but didnt have much luck.

Does this sound plausible or at least on the right track?

**Comment by tlil** [comment]
Hi @JJLost,

Did you take a look at [RelayMutationAttributeTests](https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Attributes/Execution/Relay/RelayMutationAttributeTests.cs) by any chance?

Also, I just pushed a new commit with an example; you can populate the array of `mutations` by filtering out `Assembly.GetTypes()` by types implementing `IMutation` :-) 

https://github.com/graphql-dotnet/conventions/blob/d90f4ecaa919e8670f800387aed4d97326a65788/test/Tests/Attributes/Execution/Relay/DynamicMutationRegistrationTests.cs#L26-L35

Hope that helps!

Cheers

**Comment by JJLost** [comment]
I like the idea, but these IMutation<TInput,TOutput> classes are defined in legacy code, and it seems incorrect to me to alter each of those classes and add a dependency on the Conventions library.

That being said my initial idea was to create some kind of dynamically generated Field.  This [Gist](https://gist.github.com/JJLost/70882971821082fdb20c4cce56b62f4b) is a rough example of what i was thinking.  Based roughly of the stuff in your dynamic test.

Does something like that seem plausible?
Also thank you for the prompt response.

**Comment by tlil** [comment]
Yes, that's plausible. I think the easiest approach would be to:
 - For each `TMutation : IMutation<TInput, TOutput>` you find in legacy code
     - Get graph type for `TMutation`; call the result `MutationImpl`
     - Locate field `mutate` on generated type `MutationImpl` and rename as desired
     - Append derived field to your `schemaMutation`

That way you have `GetGraphType()` doing most of the work for you. :-)

**Comment by JJLost** [comment]
I think i got what you were talking about but possibly implemented it incorrectly.

 [Updated Gist](https://gist.github.com/JJLost/70882971821082fdb20c4cce56b62f4b) Does this look correct?

However i am having issues in the FieldResolver class on the GetSource  function where the context.Source and DependencyInjector and SchemaInfo are null and it fails there.

On a side note I also kept running into an error with my introspection where some of the DefaultValues would be returned as "null" instead of null throwing a generic 

> Syntax Error GraphQL (1:1) Unexpected Name "null"
> 1:  null

**Comment by tlil** [comment]
>On a side note I also kept running into an error with my introspection where some of the DefaultValues would be returned as "null" instead of null throwing a generic

That's an incompatibility in earlier versions of GraphiQL: they don't support `null`-literals :-) Tried running a later version of GraphiQL?

**Comment by tlil** [comment]
@JJLost Will take a look at the Gist in a few days – sorry, just got back from a 4-week trip, so just catching up on all my emails :-)

**Comment by tlil** [comment]
> However i am having issues in the FieldResolver class on the GetSource function where the context.Source and DependencyInjector and SchemaInfo are null and it fails there.

Hi @JJLost, the reason why you're having that issue, is that you're not setting the `ResolvedType` and `Resolver` here:

https://gist.github.com/JJLost/70882971821082fdb20c4cce56b62f4b#file-dynamicmutationregistration-cs-L34-L35

For an example of how to do it, take a look at:

https://github.com/graphql-dotnet/conventions/blob/9932071d991049190f0f8c04d4a9805b7f622b58/test/Tests/Adapters/Engine/DynamicConstructionTests.cs#L34-L35
