### ISSUE TITLE
How to "RegisterType"

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/conventions#69]
Hi,

I want to build a schema with a interface type (InterfaceGraphType equivalent) without exposing the concrete types.

The "regular graphql-dotnet" describes hwo to accomplish this using RegistryType on the schema (see [getting started](http://graphql-dotnet.github.io/graphql-dotnet/getting-started) under RegisterType). 

How would you go about doing this using conventions?

**Comment by baluubas** [comment]
Nevermind. I had a abstract class as base and not a interface.

**Comment by tlil** [comment]
:+1:
