### ISSUE TITLE
Using InputObjectGraphType

### ISSUE THREAD

**Issue by Msirkovsky** [graphql-dotnet/conventions#71]
Hi, 

first of all, thank you for your great library. 
And I would like to ask, if I can use manual created graphQL type.

My example class:

```
public class HumanInput : GraphQL.Conventions.Adapters.Types.InputObjectGraphType<object>
{
    public HumanInput()
    {
        Name = "HumanInput";
        AddField(new FieldType
        {
            Name = "name",
            Type = typeof(string)
        });
    }
}
```
If I want to use this class for input parameter I get this error:

> Unhandled Exception: System.ArgumentException: Cannot create an instance of GraphQL.Conventions.Adapters.Types.OutputObjectGraphType`1[TType] because Type.ContainsGenericParameters is true.
>    at System.RuntimeType.CreateInstanceCheckThis()
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.CreateTypeInstance[TType](Type type)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructType[TReturnType](Type template, GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveField(GraphFieldInfo fieldInfo)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveFields(GraphTypeInfo typeInfo, IComplexGraphType graphType)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.<ConstructInterfaceType>b__21_0(GraphTypeInfo t)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructInterfaceType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetType(GraphTypeInfo typeInfo)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.<ConstructInterfaceType>b__21_0(GraphTypeInfo t)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructInterfaceType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetType(GraphTypeInfo typeInfo)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveArgument(GraphArgumentInfo argumentInfo)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveField(GraphFieldInfo fieldInfo)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveFields(GraphTypeInfo typeInfo, IComplexGraphType graphType)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveField(GraphFieldInfo fieldInfo)
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveFields(GraphTypeInfo typeInfo, IComplexGraphType graphType)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.ConstructOutputType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.GetComplexType(GraphTypeInfo typeInfo)
>    at GraphQL.Conventions.Adapters.GraphTypeAdapter.DeriveSchema(GraphSchemaInfo schemaInfo)
>    at GraphQL.Conventions.Builders.SchemaConstructor`2.Build(TypeInfo[] schemaTypes)
>    at GraphQL.Conventions.GraphQLEngine.BuildSchema(Type[] types)

**Comment by tlil** [comment]
Thanks!

You can't currently do that unless you use some boilerplate code similar to the following example:

https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Adapters/Engine/DynamicConstructionTests.cs

I would encourage you to use the library with the standard syntax instead of mixing manually constructed and derived GQL types, e.g.:

```cs
[InputType]
public class HumanInput
{
    public string Name { get; set; }
    // ...
```
