### ISSUE TITLE
Viewer without ImplementViewerAttribute

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/conventions#72]
Hi,

I think I might have stumbled upon a bug with interface resolution. The back story is this, I need an Id property on my "standard" relay viewer field. So I can't use ImplementsViewer(OperationType.Query) as QueryViewer types does not have that field. No worries, I can just create that myself. However, in doing so I seem to have broken the something with the Node field (also a relay convention).  Queries are executed, and everthing looks fine except that all properties in the response are null.

I have recreated the problem the sample project https://github.com/baluubas/conventions

I'm expecting this query to return the id
```
query ANode {
  node(id:"Qm9vazox") {
       id     
  } 
}
```

It seems ordering of the fields are importants, as this workaround solves the issue for us
https://gist.github.com/baluubas/9ddc71fe45405b9f1f3c4ba59d7283dc

**Comment by tlil** [comment]
Hi, and sorry for the late reply – been out for a month and just catching up on emails here now.

What's `id` if you add a breakpoint at https://github.com/baluubas/conventions/commit/2220ef88cf13d8d98e83c55da5e64db5160758ac#diff-5813df268429a1d149d203922f1f53e4R13? Also, do you get the object resolved if you step into `context.Get<T>()`? Can you also check what you get if you add `__typename` to the result field set for `node` in the query above?

I can take a look on my home computer here later in the week as well and see if I'm able to repro.

Cheers

**Comment by baluubas** [comment]
`id` is `Qm9vazox`.

`context.Get<T>()` returns instance of `Book`

Adding `__typename` yields this response

```
{
  "data": {
    "node": {
      "id": null,
      "__typename": "Book"
    }
  }
}
```

**Comment by tlil** [comment]
Does the same happen if you create a separate query class `NodeQuery` like so:

```cs
public class NodeQuery
{
    [Description("Retrieve book/author by its globally unique ID.")]
    public Task<INode> Node(UserContext context, Id id) =>
        context.Get<INode>(id);
}
```

and register it here:

https://github.com/graphql-dotnet/conventions/blob/9932071d991049190f0f8c04d4a9805b7f622b58/samples/SimpleWebApp/Startup.cs#L30-L34

with:

```cs
.WithQuery<Schema.NodeQuery>()
```

cc @baluubas

**Comment by baluubas** [comment]
Startup with: 
```           
 _requestHandler = RequestHandler
                .New()
                .WithDependencyInjector(dependencyInjector)
                .WithQueryAndMutation<Schema.Query, Schema.Mutation>()
                .WithQuery<NodeQuery>()
                .Generate();
```

Returns 
```
{
  "data": {
    "node": {
      "id": "Qm9vazox",
      "__typename": "Book"
    }
  }
}
```

So that seems to have solve the problem.

**Comment by tlil** [comment]
:+1: Okay, since that's the recommended way of doing this, I'll close this issue.
