### ISSUE TITLE
FieldTypes of Interface children have a null ResolvedType after execution

### ISSUE THREAD

**Issue by john-rubin** [graphql-dotnet/conventions#74]
Greetings.

I have a problem that I can't find the cause of.  When converting my return types to interface types, away from concrete types, the return dictionary's values resolve to null, even after all operations complete, and all children are iterated through.

When going through the source, I found the cause to be that:
`
                resolveResult.Value =
                    await CompleteValueAsync(context, fieldDefinition.ResolvedType, fields, result, path).ConfigureAwait(false);
`
was passing a null `fieldDefinition.ResolvedType`.  I can't find the cause of this.  When the `GraphQLEngine` instance is created, all child types are correctly assigned `ResolvedTypes`. 

This is only occurring, again, on Interface return types.  Given the following interface:
![image](https://user-images.githubusercontent.com/22896735/31024024-f79287f6-a4fa-11e7-8f0f-3bc827263663.png)

All children are iterated over, and retrieved, but the values of each child are discarded during the `CompleteValueAsync` call, due to the null `fieldDefinition.ResolvedType`.  When I go back to using the concrete type, instead of the interface type, this becomes a non issue.

I'm assuming I'm doing something wrong, but this behavior seemed odd when stepping through the source, so I thought I'd ask.

Thank you for your time.
-John

**Comment by tlil** [comment]
Hi John,

Sorry, I've been out for a month so didn't see your message until now.

That sounds weird. Could you provide some more context? Are all implementation classes of the interfaces in the same assembly that as the one you're running?

Could you provide a small sample project that demonstrates the problem so that I can take a look?

Cheers,
Tommy

**Comment by john-rubin** [comment]
Hi Tommy, no worries!

Yes, all implementations are in the same assembly.  I'll double check, and get back to you with an example.  Thanks for replying.

Kind Regards,
John

**Comment by tlil** [comment]
Hi @john-rubin, did you get any further with this?

**Comment by tlil** [comment]
Will close this - but feel free to re-open if you're still having issues.
