### ISSUE TITLE
Auto ignore Fields with Void return types and types from unwanted namespaces.

### ISSUE THREAD

**Issue by adebisi-fa** [graphql-dotnet/conventions#75]
Hello,

I ran into a use-case where fields with ```void``` return types needs to be auto-ignored, as they are not supported by ```RequestHandler.ProcessRequest(...)``` use-case (throws exception).

Similarly, although types from ```System.``` namespaces are auto-ignored during schema generation, it'll be very interesting if we are able to provide a **list/array** of other namespaces whose types should likewise be auto-ignored during this phase.

I was able to implement these features in an internal project I worked on (now in production).

Will you not mind if I send a pull request for these?

So much appreciate the wonderful work you are doing with GraphQL Convention.  It's awesome!!!

Thanks, please.

**Comment by tlil** [comment]
Hi @adebisi-fa,

Thanks for raising this. I've fixed the problem with `void` return types in https://github.com/graphql-dotnet/conventions/pull/78. Sorry, I thought I'd fixed that earlier, but I obviously hadn't :-)

I will take a look at the PR that you raised for unwanted namespaces, and get back to you on that on the PR itself, so will close this issue so we only communicate in one place.

Cheers,
Tommy
