### ISSUE TITLE
Using the Nuget Library with GraphQL 2.x.x alpha

### ISSUE THREAD

**Issue by drobertson123** [graphql-dotnet/conventions#80]
I am attempting to use the Conventions Library in a project that is based on GraphQL-dotnet. When I add your Nuget library it causes all kinds of conflicts with the namespaces.

Am I misunderstanding something? I had assumed this is an extension of the GraphQL library, should I be using it as a replacement instead?

How do I use your library?

Thanks for the help.

**Comment by joemcbride** [comment]
It was originally an extension, though it now uses a fork of the core project (included in the source).  So I believe to use this lib you would need to only reference the Nuget for this project.

@tlil can talk to any plans to bring it back as an extension of the core library.

**Comment by tlil** [comment]
As @joemcbride states above, the Conventions library currently has a bundled copy of the graphql-dotnet library with some tweaks that are not present in the upstream repo. So, to use Conventions, you'd have to remove the dependency on graphql-dotnet and use the bundled copy instead.

I'm aware that the bundled copy of the library is a bit behind `master` on [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet), but I've got plans to update that soon.

Hope that helps.

Which version are you currently using btw? https://github.com/graphql-dotnet/graphql-dotnet/releases

**Comment by drobertson123** [comment]
Thanks, that clears things up.  My vote would be an extension, but I can understand how they drift apart and splitting the source helps that.

I am really liking where graphql-dotnet is going. In fact, it is at the core of a major project we are working on. (happy to share on a more private channel)

One area that we are running into challenges is configuration. Our system has about 12 major projects. Each one has its own GraphQL types, queries, mutations, schemas, etc... Creating a nice simple and standardized way to add all of those together is a lot of work. Currently, it involves a fair amount of fragile code.

There are some features in Conventions that would be great to just have in the main project. I was specifically looking for the ability to merge schemas. I am building a basic framework to load parts of a final schema from configuration modules (I am using autofac) that I load at startup. The ability to merge schemas would be a huge help doing this.

Thanks for the great work and updating me.

I am currently working on the Version 2.0.0-alpha-802 that doesn't seem to be on that list. Is there a general Nuget source for the latest alphas?

**Comment by Igorbek** [comment]
I would also much more prefer it be an extension. Are any plans to move back towards the extension architecture? Should we create an issue to track progress/status on that?

**Comment by drobertson123** [comment]
FYI, I amazingly discovered that I didn't have the Allow Pre Release set for GraphQL.NET in Nuget. Feeling a bit stupid now. I am using the Version 2.0.0-alpha-820 and updating as the new ones come out.

On a side note unrelated to this project, it would be great if allow pre-release was capable of being set per library. I want the pre-release on GraphQL.net but I don't want every pre-release for every library.

**Comment by drobertson123** [comment]
A general question for you. What would it take to decouple conventions from the GraphQL-dotnet code?

Was the conventions code intermingled with the graphql-dotnet code or is it fairly separate? Is there any way to tell what is what?

I am just curious to take a swing at migrating Conventions to the new version of graphql-dotnet and want to see if I am insane for even trying.

An alternative would be to see if there is support for merging conventions into graphql-dotnet propper. It seems like some of the concepts you have here are very good and would be useful in the main code.

I understand the idea of keeping graphql-dotnet pure and focused (a good goal), but the industry is already expanding beyond the GraphQL spec with features that are being widely adopted. Apollo has many features like this. As long as the outside interface stays true to and only expands the GraphQL standards then I see additional features as a good thing.

The .NET side also has a disadvantage. We don't have the huge ecosystem of NPM and similar packages of small tools. Nuget is great, but it is more focused of full-fledged libraries. NPM fills in the gaps for connecting to back-end data. We don't have as full a toolset on the .NET side (at least for GraphQL.)

In my mind, this argues for a more feature rich connection to the data and business layers. Conventions could be an effective part of that.

**Comment by bert2** [comment]
I'm trying to use GraphQL.Conventions alongside Dapper.GraphQL, which depends on GraphQL. Due to the namespace conflicts that won't be possible, I guess.

Is there any chance for this package to go back to the old extension setup or will GraphQL definitely stay inside GraphQL.Conventions for good?

**Comment by tlil** [comment]
Hi @bert2 - yes, it's on my todo list. Just haven't gotten to it yet, sorry. I hope to have some time next week to work on it. Shouldn't take much work to get it split out into a pure extension library, and that was always the plan anyway.

For reference, what version of the underlying GraphQL.net library are you using at the moment? Any requirements?

**Comment by bert2** [comment]
Hi @tlil , that sounds great! Thanks for the update!

I have no requirements regarding the GraphQL version. It's just that I'd like to use your library together with another library also built on top of GraphQL. However, due to the namespace conflicts I cannot use your library at the moment and installed GraphQL v0.17.3 again. But like I said: for me it's really not about the GraphQL version. I'm doing only basic stuff and don't need the latest features.

**Comment by tlil** [comment]
@drobertson123 @bert2 I've pushed a WIP branch: https://github.com/graphql-dotnet/conventions/tree/engine-update

There are a few things that need fixing in the graphql-dotnet library, so I've had to disable and ignore some tests for now. But was hoping you could take the branch for a spin and see if it works for what you're trying to do. Note, it's based on the _latest alpha_ release of @joemcbride's GraphQL.NET library to include things like `null` literals, etc.

**Comment by tlil** [comment]
cc @Igorbek ^

**Comment by drobertson123** [comment]
Thanks for that.  I will poke around and see how it goes.

**Comment by tlil** [comment]
Closing this issue as it's now being handled in https://github.com/graphql-dotnet/conventions/pull/82. Close to merging, just need the latest release from [graphql-dotnet/graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet)

**Comment by tlil** [comment]
@drobertson123 FYI, 1.4.0 is released.
