### ISSUE TITLE
GraphQL queries expected to be json?

### ISSUE THREAD

**Issue by ronnyek** [graphql-dotnet/conventions#81]
I just tried to start integrating this into one of my projects and I've noticed that queries I run in graphiql fail to run against my stuff.

It looks like at some point graphql conventions is attempting to parse query as json and failing. Looking at the examples, they all seem to also specify query in json format. It seems like this is both valid syntax and definitely not standard json. 

```
query starwarsQuery {
  allFilms{
    films {
      id,
      title,
      releaseDate,
      director   
    }
  }
}
```

**Comment by ronnyek** [comment]
I attempted this with both requesthandler and just creating a new engine and executing with requestbody

**Comment by tlil** [comment]
Correct - GraphQL takes a request in the form of a composite of query, variables and operation name. This payload is typically submitted as a JSON blob.

Take a look at: https://github.com/graphql-dotnet/conventions/blob/master/test/Tests/Web/RequestTests.cs

You can also create a `Request` from `QueryInput`. :-) Hope that helps.
