### ISSUE TITLE
Use Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#83]
ASP.NET Core has a published DI library that is similar to the one defined and implemented in this library.

https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/

It might be worth importing it directly for better integration with the rest of the ecosystem.

**Comment by huysentruitw** [comment]
And what with non-ASP.NET Core users?

This shouldn't be an issue as it's easy to implement. F.e. our implementation to integrate with Autofac looks as simple as:

    internal sealed class Injector : IDependencyInjector
    {
        private readonly ILifetimeScope _scope;

        public Injector(ILifetimeScope scope)
        {
            _scope = scope;
        }

        public object Resolve(TypeInfo typeInfo) => _scope.Resolve(typeInfo);
    }

    // Registration:
    services.Builder.RegisterType<Injector>().As<IDependencyInjector>().InstancePerLifetimeScope();

You could create a separate package with an implementation for `Microsoft.Extensions.DependencyInjection` but that might not be worth the effort of keeping it up to date.

**Comment by tlil** [comment]
To be honest, I'd rather keep the library "pure" and less opinionated about what DI library to use. As @huysentruitw points out, it shouldn't be much work plugging it in (and if for some reason it isn't, please do let me know so that I can check how it can be made easier). (Also, as @huysentruitw points out, integrating with ASP.NET Core is not the only way of using this library :))

**Comment by infogulch** [comment]
> integrating with ASP.NET Core is not the only way of using this library

This is a completely reasonable justification for not pulling in ASP.Net dependencies.

I ended up wrapping it almost identically for ASP.Net. Uncannily similar in fact, except the conversion from TypeInfo into Type.

```
    public class DependencyInjectorWrapper : IDependencyInjector
    {
        private ServiceProvider _sp;

        public DependencyInjectorWrapper(ServiceProvider sp)
        {
            _sp = sp;
        }

        public object Resolve(TypeInfo typeInfo) => _sp.GetService(typeInfo.AsType());
    }
```

I mostly wanted a discussion and that's what I got! So feel free to close the issue. :)

**Comment by tlil** [comment]
:+1: Thanks – glad you got it working
