### ISSUE TITLE
Access resolution objects after .Execute()?

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#84]
Is there a way to access the query/output objects after the resolution and execution has completed?

I would like to have a mutation that has non-visible side effects, but apply it *after* Execute() has completed and the side effects have been evaluated.

To get a bit more concrete example, I'd like to have a `login` mutation that adds a cookie. E.g.

```
public class LoginResult
{
    // etc...
    [Ignore]
    public CookieData Cookie;
}
public class Mutation
{
    public Task<LoginResult> Login([Inject] Stuff stuff, string username, string password)
    {
        ...
        if (verified) return LoginResult() { ..., Cookie = new cookie... };
    }
}
```
Then in my executor
```
var result = engine
  .NewExecutor()
  .WithUserContext(user)
  .WithRequest(requestBody)
  .Execute();

var cookie = (result.[something...] as LoginResult)?.Cookie;

if (cookie != null) Response.Cookies.Add(cookie)
```

I would prefer to add this to a query result to make it easier to unit test, since the side-effects don't happen until after everything returns. Another option would be to add them to the IUserContext, though I would prefer the other for the reasons stated.

Is this possible? Is there a different way to look at this, or am I completely off my rocker here?

**Comment by huysentruitw** [comment]
You're probably using ASP.NET Core, so I'm not sure how to do it there, but you could do something similar to what one would do with OWIN: use the CookieAuthentication middleware and resolve the `IOwinContext` in the field-resolver (by using `[Inject]`) and challenge the cookie authentication middleware by calling `owinContext.Authentication.Challenge(...)`.

If you don't want to use the existing cookie middleware, you can mimic this by writing Challenge/Get extension method that writes/reads a value to the current request environment.

**Comment by tlil** [comment]
Ditto what @huysentruitw said.

If that's not an option for you, I can't see the issue with extending `IUserContext`?

>I would prefer to add this to a query result to make it easier to unit test, since the side-effects don't happen until after everything returns. Another option would be to add them to the IUserContext, though I would prefer the other for the reasons stated.

By mocking or having a custom implementation of `IUserContext`, surely you can easily test for the side-effects in your unit tests? E.g., see how `userContext` is passed into `ProcessRequest`: [GraphQL.Conventions/Web/RequestHandler.cs#L233](https://github.com/graphql-dotnet/conventions/blob/master/src/GraphQL.Conventions/Web/RequestHandler.cs#L233)

**Comment by infogulch** [comment]
@huysentruitw that's an interesting idea that I'll have to explore more.

@tlil This is what I went with (it's the most straightforward) it just feels dirty to shuttle actionable data out *through* the IUserContext impl. By which I mean, no, I don't have any concrete reasons why this can't work. :P

Thanks for the feedback. :)
