### ISSUE TITLE
NonNull annotation for input types

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#85]
Is it strictly necessary for class fields that correspond to GraphQL Fields to be wrapped in `NonNull<>` to set `IsNullable = false`? I think it makes interacting with non nullable input fields more cumbersome than it needs to be.

Instead could this be an annotation on the field? This wouldn't affect normal usage of the field, and since GraphQL.Net checks the type when decoding the query this shouldn't be a problem internally.

Maybe it's still useful for output & query types to ensure internal correctness, but even there it could be a check instead of a new type.

Thoughts?

**Comment by tlil** [comment]
Closing this as it's superseded by your PR #86
