### ISSUE TITLE
Conventions.Relay required or optional (practically)?

### ISSUE THREAD

**Issue by PtwHub** [graphql-dotnet/conventions#87]
Is this conventions handler made to (or intended to) be also used without Conventions.Relay? I am using an Apollo Client...

Any tips/pointers appreciated.

**Comment by tlil** [comment]
What exactly are you trying to do, sorry?

There exist some types to help with Relay specific functionality, but most of this is just a thin layer on top anyway, so there's no reason why you can't go with your own solution as well.

https://github.com/graphql-dotnet/conventions/tree/master/test/Tests/Types/Relay

**Comment by PtwHub** [comment]
Thanks. I'm trying to hear from one of the developers if this is relay-coupled or not since the example and many tests use relay since I am not using relay (apollo2). OK, I'll check the sources some more.

**Comment by tlil** [comment]
Okay, no worries. Let me know if any more questions come up. :)
