### ISSUE TITLE
Battle test v1.4.0 in production environment

### ISSUE THREAD

**Issue by rodolfotorres** [graphql-dotnet/conventions#88]
## Description
As part of the role out of v1.4.0 we want to battle test on a production environment and see if any issues come up.

- [x] Add v1.4.0 to one of our clusters and run api tests
- [x] Deploy it to prod

**Comment by rodolfotorres** [comment]
I tried to install v1.4.0 but is throwing an error ```Unable to find a version of 'GraphQL' that is compatible with 'GraphQL.Conventions 1.4.0 constraint: GraphQL (>= 2.0.0-alpha-887)'.```
What am I missing?

**Comment by rodolfotorres** [comment]
_Update_: I was able to go around it by installing the pre-release version of `GraphQL` first. 🤔 do we know when the engine will go to release?

**Comment by rodolfotorres** [comment]
There are 2 breaking changes
* `'ExecutionErrors' does not contain a constructor that takes 1 arguments`
* '`LegacyExecutionResult' does not contain a definition for 'Extra' and no extension method 'Extra' accepting a first argument of type 'LegacyExecutionResult'`

None are hard to solve but I thought it might be worth calling it out

**Comment by rodolfotorres** [comment]
<img width="361" alt="screen shot 2018-04-26 at 11 49 39" src="https://user-images.githubusercontent.com/5260155/39301706-04b17446-4948-11e8-9568-466beb825f9e.png">

**Comment by tlil** [comment]
@rodolfotorres :+1: Thanks for testing. If the 2 changes that you're mentioning are easy to fix your end, that'd be great. I'd prefer not to keep 'legacy' stuff in the library itself. The `LegacyExecutionResult`, IIRC, is a Hudl-specific class, and `Extra` is now essentially `Extensions` (aligned with the engine).

Regarding:
> Update: I was able to go around it by installing the pre-release version of GraphQL first. 🤔 do we know when the engine will go to release?

@joemcbride, any ETA for when v2 will be out (a non-alpha version)?

**Comment by rodolfotorres** [comment]
@tlil We released one of our services with v1.4.0. I will continue to monitor for the next couple of days but it's looking good so far

**Comment by tlil** [comment]
Great, thanks @rodolfotorres
