### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by rodolfotorres** [graphql-dotnet/conventions#89]
## Description
There were recent changes to `graphql-dotnet` to support subscriptions. With version 1.4.0 we can now build an example of how subscriptions work with conventions.

- [x] Support for subscriptions
- [x] Add an example for how subscriptions work

**Comment by tlil** [comment]
How are you getting on with this one @rodolfotorres ?

**Comment by dmg-hamann** [comment]
I actually tried to add subscription support. It works with the GraphQL.Server package. I added an example solution where it is possible to play around on the graphql.playground. 

Do you (@tlil ) think this goes in the right direction?
[Branch](https://github.com/dmg-hamann/conventions/tree/subs) 

The following points I dislike about my current solution:

- I did not integrate setting the websocket stuff within the engine
- To work correctly via di I needed to add a DocumentExecutor which just wraps _engine.NewExecutor().WithDependencyInjection()

**Comment by tlil** [comment]
Ah, awesome! Let me have a look over the weekend, @dmg-hamann. Will get back to you.

**Comment by tlil** [comment]
@dmg-hamann - looks great! Thanks for doing that. Want to raise a PR? I'd love to get this into the main repo :-)

As for the two points that you're raising:

>I did not integrate setting the websocket stuff within the engine

I think that is fine as a first step. If you raise a PR, I'll get it in, and then I'll do a follow-up PR where I can look at getting that sorted as well. I've got a few other improvements lined up anyway, some general tidy up, etc., so this can naturally get absorbed by that work. Sound good?

>To work correctly via di I needed to add a DocumentExecutor which just wraps _engine.NewExecutor().WithDependencyInjection()

Yep, saw that.  Similar to the above, I can take a look at tidying that up in my follow-up PR.

Last thing, mind adding some unit tests for the added functionality? :-)

Again, thanks for this!

**Comment by dmg-hamann** [comment]
@tlil Cool I am glad that it works out for you. I add some unittests today or tomorrow and raise a pr afterwards.

**Comment by tlil** [comment]
Great, thanks!

**Comment by tlil** [comment]
Closing as tracked by PR #143
