### ISSUE TITLE
Generating InterfaceGraphTypes and OutputObjectGraphType incorrectly?

### ISSUE THREAD

**Issue by ronnyek** [graphql-dotnet/conventions#9]
So I'm trying to use conventions to do some manual mapping as previously discussed in the issues section of the graphql-dotnet github repo.

I'm basically reproducing the typical starwars example you see everywhere for graphql examples... and seeing some discrepancies between this and other libraries. I'm basically using DeriveType() to take high level classes marked with attributes I specify and generate GraphTypeInfo which I then derive and register with the basic schema. If I don't explicitly call registertype for the episode enum, I get weird results... if I try to add the enum type, I get an error in graphql-dotnet itself saying "Only add root types"

Here's what I'm getting as the result of the schema generation with my hybrid blend of my stuff, and conventions
```
type Droid implements InterfaceGraphType`1 {
  appearances: [OutputObjectGraphType`1]
  id: Int!
  name: String
  primaryFunction: String
}

type Friendship {
  droid: Droid
  droidId: Int!
  friendshipId: Int!
  human: OutputObjectGraphType`1
  humanId: Int!
}

type Human implements InterfaceGraphType`1 {
  appearances: [OutputObjectGraphType`1]
  homePlanet: String
  id: Int!
  name: String
}

interface InterfaceGraphType`1 {

}

type OutputObjectGraphType`1 {

}
```

vs the schema I get from the star wars examples in graphql-dotnet (appearances etc I understand why there is a little variation...

```
enum Episode {
  A_NEW_HOPE
  EMPIRE_STRIKES_BACK
  RETURN_OF_THE_JEDI
}

interface Character {
  name: String
}

type Droid implements Character {
  droidId: Int!
  name: String
  primaryFunction: String
  appearsIn: [Episode!]
  friends: [Character]
}

type Human implements Character {
  humanId: Int!
  name: String
  homePlanet: String
  appearsIn: [Episode!]
  friends: [Character]
}
```

Didn't know if you would expect this, or if there needs to be support added for this? I was trying to add unit tests, but for whatever reason I cant run unit tests within the context of the annotations project (something about how the test project references the library

**Comment by tlil** [comment]
Can you post the code you're using to generate schema @ronnyek ?

**Comment by ronnyek** [comment]
Hmm not easily... I'll see about fixing the solution so I can get a unit test going building stuff out very plain vanilla... see if I get the same type of results... but it should be able to accomodate interfaces and enums?

**Comment by tlil** [comment]
Yes, there are some examples [here (GraphQLEngineTests.cs#L51)](https://github.com/graphql-dotnet/conventions/blob/be796d36f7057e2e528b6da8c57f15fc4cd4a98c/test/GraphQL.Conventions.Tests/Adapters/Engine/GraphQLEngineTests.cs#L51):

![image](https://cloud.githubusercontent.com/assets/5948145/21855849/c077a4fa-d817-11e6-932f-309dfff71a29.png)

Resulting in:

```graphql
type ExtendedVersion implements ISemanticVersion {
  branchName: String!
  majorVersion: Int!
  minorVersion: Int!
  revision: Int!
}
interface ISemanticVersion {
  majorVersion: Int!
  minorVersion: Int!
  revision: Int!
}
```

`enum`'s should also work (see for instance [this test method](https://github.com/graphql-dotnet/conventions/blob/541578a2b9c6d39d059c5223ab8b52a046f04b78/test/GraphQL.Conventions.Tests/Attributes/MetaData/NameAttributeTests.cs#L55)).

**Comment by ronnyek** [comment]
hmm, that does seem to work for me (creating an object to hard code the schema, but maybe thats just how things have to be) Other than one other minor thing... if my objects implement two interfaces, it just lists same interface twice.

**Comment by tlil** [comment]
Oh, really @ronnyek ? If that's the case, that's a bug :( I will add a unit test for that and verify / fix accordingly.

**Comment by tlil** [comment]
And yes, if I understand you correctly, that's what this library is intended for: Generate GraphQL schemas from defined .NET type hierarchies. Not dynamically creating ones outside of that. If you post more details about what you're trying to do though, I might see if there's a use-case for it and see if that can be supported.

**Comment by ronnyek** [comment]
I'm just trying to build some conventional based automatic graphql schema generation. I don't intend to get too crazy with the objects/entities that get returned themselves....

So I've got a "schemabuilder" that effectively wraps up conventions/annotations... and ultimate goal would be to in our apps intialization just call SchemaBuilder.Build() (much like what you have in your library).

The only thing thats really different, I dont want to have a static top level class for root/query. 

So lets say I have a UserRepository (marked up with [GraphQlEnabled("Users")]) and a DroidsRepository(marked up with [GraphQlEnabled("Droids")]). Starting the app would build what a lot of the starwars examples would. 
```
type UserRepo {
   AllUsers: <however a func is denoted>
   UserById: <func taking id>
}
...
type Query {
   Users: UserRepo
   Droids: DroidRepo
}
```

Its kinda funny because I think graphql-dotnet itself, annotations, and conventions all complete a bit of this puzzle... 

I think if I can build a GraphTypeInfo that I can set to query manually, I'll be good actually.

I don't think there are necessarily action items on your part, probably me getting a better understanding and fumbling my way through this stuff some more =)

Thanks!

**Comment by tlil** [comment]
:+1: Will get back to you with some more thoughts over the weekend.

**Comment by ronnyek** [comment]
Sweet, yeah I don't know if it even makes sense to make changes here to be honest... 

I played with this a bit. I played with the idea of modifying a schema definition to take an object instead of generic type parameter. And that came with its own challenges. That's kind of what I was implying with the compositing this and annotations or just pure graphql-dotnet.... I'd be able to just say construct a schema, for the query, construct a GraphTypeInfo with fields that were lists of objects or funcs, and for types that go down the chain from there, I'm happy to DeriveType().(currently cant do this because graphtypeinfo is basically tied to a type... and even if it wasnt, I'm not sure I could go from the GraphSchemaInfo to a functional engine instance)

In any case I appreciate the advice and input.

**Comment by tlil** [comment]
There are a few different ways that you can go about this. The easiest is probably to:

1. Derive an instance of `IGraphType` for the return type of the field that you want to add (`GraphTypeAdapter.DeriveType`), i.e. the type descriptor for the repository itself.
2. Manually add a field on the `Query` object according to your specification.

**Example:**
Say that you want to add a field `users` of type `UserRepo` to the schema's query object:
1. Call `ITypeResolver.DeriveType(typeof(UserRepository))` to get a `GraphTypeInfo` instance representing your user repository.
2. Then, call `GraphTypeAdapter.DeriveType(userRepoGraphTypeInfo)` and assign the resulting `IGraphType` to `userRepoType`.
3. Create a custom `IFieldResolver` that takes one constructor argument and returns that one in `public object Resolve(ResolveFieldContext)`.
4. Add a new field, `FieldInfo { Type = userRepoType, Name = "users", Resolver =  new CustomResolver(_userRepository) }`, to the GraphQL type `Query` using the underlying `graphql-dotnet` library.

For details on how the `GraphTypeInfo` gets constructed, take a look at `Types/Resolution/TypeResolver.cs`. The translation from `GraphTypeInfo` to `IGraphType` takes place in `Adapters/GraphTypeAdapter.cs`.

Excuse my brevity. Hope that helps.

**Comment by tlil** [comment]
@ronnyek re:
>if my objects implement two interfaces, it just lists same interface twice.

I committed https://github.com/graphql-dotnet/graphql-dotnet/compare/12726ac79dcabe9b492f98e1ecc392d95e4389a6...6b806c2aa3b6adfa974621a0ae3666430c603971#diff-3173ce489fac4523f0479aef1c4b48a9 as part of https://github.com/graphql-dotnet/conventions/commit/88a2afa64c9419234574b361454cc352b4661a5a to fix that – thanks for reporting!

AppVeyor seems to be having problems right now, but the fix will be made available in version 1.0.7 once they're back up and running.

**Update**: New version is up.

**Comment by ronnyek** [comment]
> Add a new field, FieldInfo { Type = userRepoType, Name = "users", Resolver = new CustomResolver(_userRepository) }, to the GraphQL type Query using the underlying graphql-dotnet library.

I believe I get what you are saying there... if I pass userRepoType in like that in for type like below, I just get a OutputObjectGraphType`1 as the type for the userRepo etc.  I dont see anyplace it'll let me pass a non type to Type, nor do I see anyway to add a field with a FieldInfo type like that.

```
 var enabledAttribute = x.GetCustomAttribute<GraphQLEnabledAttribute>();
                var graphTypeInfo = typeResolver.DeriveType(x.GetTypeInfo());
                var graphType = typeAdapter.DeriveType(graphTypeInfo);
           
                var field = query.Field(graphType,
                    enabledAttribute.Name, 
                    description: enabledAttribute.Description);
```

query in this case is just a new ObjectGraphType, but almost feel as if I'm using a different version of graphql-dotnet or something.

**Comment by ronnyek** [comment]
I believe if I explicitly set ResolvedType to that graphtype, it just overwrites what it was using for type, but I still have to pass the type in as well. This may get me going =)

**Comment by tlil** [comment]
@ronnyek See https://github.com/graphql-dotnet/conventions/commit/d27b4abcdb91d14717af64228f4d61e96325c476 for an example of how you can solve it. I'll close this issue now, but feel free to reopen if that doesn't cover what you needed.

**Comment by ronnyek** [comment]
Ok that helped immensely... In an effort to track down, I basically took that demo test, appended enum data, and it starts failing the way I see it failing on my side.

```
 enum UserFlag
        {
            IsAdmin,
            IsUser
        }
        class User
        {
            public string Id { get; set; }

            public string Name { get; set; }
            public UserFlag UserFlag { get; set; }
        }


//making sure  the resolve accommodates this type
if (t == typeof(UserFlag))
                {
                    return userFlagType;
                }

this blows up schemaprinter because its not resolving type properly, and passing null into resolve name.
```

**Comment by tlil** [comment]
Have you registered the type like this?

https://github.com/graphql-dotnet/conventions/commit/d27b4abcdb91d14717af64228f4d61e96325c476#diff-51df35b777650eeee206ab5fd1c92592R26

and

https://github.com/graphql-dotnet/conventions/commit/d27b4abcdb91d14717af64228f4d61e96325c476#diff-51df35b777650eeee206ab5fd1c92592R33

**Comment by ronnyek** [comment]
Well I wasn't registering with the schema, but I forgot that I wasn't doing that, because if I try and register the graph type generated from the enum, it detects as a "NonNullGraphType" and blows up with "Only add root types".

**Comment by tlil** [comment]
Try registering `UserFlag?` ? Does that work?

**Comment by ronnyek** [comment]
schema.RegisterTypes(Type[]) wont let me register a simple Enum saying its not of GraphType type, and if I schema.RegisterTypes(userGraphType), its blowing up with the only add root types bit.

**Comment by tlil** [comment]
@ronnyek I meant something like this (untested – can have a closer look later):

```cs
var userFlagEnumType = GetGraphType(
    typeAdapter,
    typeResolver,
    typeof(UserFlag?).GetTypeInfo());
// (...)
schema.RegisterTypes(
    userFlagEnumType,
    userType,
    userRepositoryInterface,
    userRepositoryType);
```

**Comment by ronnyek** [comment]
Oh sorry, nullable type, I thought the first question mark was just erroneous... I'm definitely almost there with everything else though. Appreciate the time!

**Comment by lp4793fg** [comment]
@tlil Your example is very helpful. Thank you so much.
I'm kind stuck on something tho, 

Here's an exact code snippet from your example -
`            var typeAdapter = new GraphTypeAdapter();
            var typeResolver = new TypeResolver();

            var userRepositoryInterface = GetGraphType(typeAdapter, typeResolver, typeof(IUserRepository).GetTypeInfo());
            var userRepositoryType = GetGraphType(typeAdapter, typeResolver, typeof(UserRepository).GetTypeInfo());
            var userType = GetGraphType(typeAdapter, typeResolver, typeof(User).GetTypeInfo());

            var schema = new Schema
            {
                Query = new ObjectGraphType { Name = "Query" }
            };

            schema.RegisterTypes(userType, userRepositoryInterface, userRepositoryType);

            schema.Query.AddField(new FieldType
            {
                Name = "users",
                ResolvedType = userRepositoryType,
                Resolver = new CustomResolver(new UserRepository()),
            });

            var schemaDescription = new SchemaPrinter(schema).Print();
            schemaDescription.ShouldEqualWhenReformatted(@"
            interface IUserRepository {
                getUserById(id: String): User
            }
            type Query {
                users: UserRepository
            }
            type User {
                id: String
                name: String
            }
            type UserRepository implements IUserRepository {
                getUserById(id: String): User
            }
            ");

            var executer = new DocumentExecuter();
            var result = await executer.ExecuteAsync(schema, null, "{ users { getUserById(id: \"1\") { id name **manager { idd }** } } }", null);
        }

        private IGraphType GetGraphType(GraphTypeAdapter typeAdapter, TypeResolver typeResolver, TypeInfo typeInfo)
        {
            var graphTypeInfo = typeResolver.DeriveType(typeInfo);
            return typeAdapter.DeriveType(graphTypeInfo);
        }

        class CustomResolver : IFieldResolver
        {
            private readonly UserRepository _userRepository;

            public CustomResolver(UserRepository userRepository)
            {
                _userRepository = userRepository;
            }

            public object Resolve(ResolveFieldContext context) =>
                _userRepository;
        }

        class User
        {
            public string Id { get; set; }

            public string Name { get; set; }

            **public Manager Manager { get; set; }**
        }

        class Manager
        {
            public string Idd { get; set; }
        }

        interface IUserRepository
        {
            User GetUserById(string id);
        }

        class UserRepository : IUserRepository
        {
            public User GetUserById(string id) =>
                new User
                {
                    Id = id,
                    Name = $"User #{id}",
                    **Manager = new Manager()
                    {
                        Idd = "123"
                    }**
                };
        }`

I just added a child entity (Manager) under User.
I now get `Cannot query field "idd" on type "OutputObjectGraphType`1".`
I feel like I'm missing how to register the Manager type. Is there a way to set a default resolver, and auto serialize it from the User object we got?

How can I set up default/specific resolver for a child entity?
