### ISSUE TITLE
Using conventions in .NET Core 2... any example?

### ISSUE THREAD

**Issue by jordisan** [graphql-dotnet/conventions#92]
Hi... good idea, and good job!

I wonder if conventions are supposed to work in a .NET Core 2 project using MVC, like this one: https://github.com/JacekKosciesza/StarWars/tree/master/StarWars.Api

I mean... how would you add conventions to it? Thanks.

**Comment by rodolfotorres** [comment]
I think I have an example of what you are looking for: https://github.com/rodolfotorres/graphql-api

**Comment by jordisan** [comment]
Thanks a lot, @rodolfotorres ... I'm trying to adapt that example to our code 😃

**Comment by tlil** [comment]
Great - thanks @rodolfotorres. I'll close this ticket @jordisan, but feel free to reopen if you run into any problems.
