### ISSUE TITLE
Is there any kind of documentation?

### ISSUE THREAD

**Issue by shoooe** [graphql-dotnet/conventions#94]
I'm trying to work with this library but I can't seem to find any documentation except for the brief README and some examples.

For example, how can I throw my own errors? How can I use this in a controller (the samples seem to use a middleware)?

**Comment by rodolfotorres** [comment]
Hi @Jefffrey. For the controller you can check this https://github.com/graphql-dotnet/conventions/issues/92

**Comment by tlil** [comment]
Hi,

Yes, documentation is on my TODO list but unfortunately not gotten around to that yet. Apologies. Let me know if Rodolfo's example helps. As for how to throw your own errors, you can simply throw an exception from any of the resolvers. I'll get back to you with more info later when I'm in front of a computer.

Cheers
