### ISSUE TITLE
Inject on class constructor

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#95]
Would it be possible to use the DI to inject values into the class constructor of the main Query and Mutation classes?

**Comment by infogulch** [comment]
Does this make sense? Or is this idea just silly to begin with?

**Comment by tlil** [comment]
You already can, take a look at `DependencyInjectionTests.cs` in the `Tests` project. The `Query` class has a constructor that takes an `IRepository` as input. Is that not what you mean?

**Comment by infogulch** [comment]
Oh! I tried it and it didn't seem to be working, but I must have done something wrong. I'll look again.

Thank you for the pointers, sorry for the noise!

**Comment by tlil** [comment]
Perhaps you forgot to register the dependency injector? :) No problem

**Comment by infogulch** [comment]
Ok so I just tried again and I'm running up against the same problem I did before.

I'm using EF for connecting to my database, and if I have the dbcontext injected directly into the method it works great, and it has been working great for several months, but that's rather tedious/redundant given that every resolver needs the dbcontext (hence the question).

But if I convert it to inject the dbcontext into the constructor I get a "No database provider has been configured for this DbContext" error. My handler looks like this:

```c#
var result = await engine
  .NewExecutor()
  .WithUserContext(user)
  .WithDependencyInjector(di)
  .WithRequest(requestBody)
  .Execute();
```
And `engine` is:
```c#
// note: it does the same thing when not static
private static readonly Lazy<GraphQLEngine> _engine = 
    new Lazy<GraphQLEngine>(() => GraphQLEngine.New<API.Query, API.Mutation>());
private GraphQLEngine engine => _engine.Value;
```

So, yes it seems to be a dependency injection issue, but I'm not sure how to fix it. Since di is set per request, but it seems that the the Query and Mutation classes are instantiated without it.

Am I doing something wrong here? I'm guessing this is gonna turn into one of those "how did this ever work for me in the first place?!?" situations.

**Comment by infogulch** [comment]
Ok so it looks like if I create a new engine on each request with: `GraphQLEngine.New([Func<Type, object>()])` it works fine.

So I guess my question becomes: what's the difference between the optional injector function on New(), and `.WithDependencyInjector()` on the engine builder, and why is there a difference?

And then I guess: In general, should I be using a singleton engine instance like this or create a new one on every request?

**Comment by hitaspdotnet** [comment]
Dear @infogulch you got the solution? I have same issue, can you share your customized engine please?

**Comment by infogulch** [comment]
Sorry @hitaspdotnet, I haven't customized anything. My "solution" above was to create a new engine instance every time I want to use it instead of using a singleton that is preserved across requests. (When I said "new engine" in my previous comment I didn't mean a customized engine, I mean a new *object instance*. Sorry if my wording was confusing there.)

My previous comment should be enough information to work around this, are you sure you're running into this issue?

**Comment by hitaspdotnet** [comment]
@infogulch Sorry, My English isn't good and web translators not well for comments with codes. 
Actually, I'm using [ABP Framework](https://github.com/aspnetboilerplate/aspnetboilerplate) in my application. It's a modular framework. I want to use GraphQL libraries to create GraphQL end point for each application module. I could do it by the main library but because my application has 31 module I'm looking for easier way like schema generation from exciting classes or DbContext.

If possible, can you guide me on this please?

**Comment by tlil** [comment]
@infogulch could you try putting the DB context on the user context? E.g., in the object passed into:

```cs
.WithUserContext(user)
```

Take a look at `samples/SimpleWebApp/UserContext.cs`. Let me know if that helps.

Will close this for now, but feel free to re-open if that doesn't resolve your issue. Thanks.
