### ISSUE TITLE
Attribute phase between metadata & execution?

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/conventions#96]
I'm implementing custom authorization via an extended `ExecutionFilterAttributeBase` (like #22), and I found that Execution Filter is executed on each field resolution, even when this field and path has been executed before.

E.g. if I authorize on the person.name field, and a query with a list of people returns 3 entries, the attribute is called 3 times with paths `person.0.name`, `person.1.name`, `person.2.name`.

Is there any way to have this only execute once instead, and for all queried fields before any are actually resolved?

**Comment by tlil** [comment]
If you want to integrate with https://github.com/graphql-dotnet/authorization, you could use a meta-data attribute to populate the policy up-front and rely on graphql-dotnet/authorization to do the checking? There is no way of having the filter to only execute once per unique field at the moment unless you hand-roll field memoisation and keep track of what you've already checked yourself. Hope that helps.

**Comment by infogulch** [comment]
At first look /authorization seemed to be a jackhammer when I wanted a staple. My user context has a simple array of permissions that I'd like to check against the permissions set on the resolver/field via attribute. Maybe my first look was mistaken, I'll look again. :)

But actually I had a second reason why I wanted this feature: If I had this I think I could graft a system to make Entity Framework build and execute a single minimal sql query that would serve any arbitrary nested graphql query, just by passing some info to an attribute and using EF navigation properties, no dataloader necessary.

Thank you!

**Comment by tlil** [comment]
I'll close this issue, but let me know if you ended up having further questions related to this.
