### ISSUE TITLE
Multiple mutations and nested mutation

### ISSUE THREAD

**Issue by GOVYANSONG** [graphql-dotnet/conventions#97]
I am fairly new to graphql in general and convention packagein particular. Our environment is react GUI front and asp.net core web / web API server. Our plan is to use apollo client and graphql dotnet as query gateway. I would like to know if your package supports following feature over HTTP POST:

1. Multiple mutations in one http post request: I was using engine.withrequest() method. But I did not see how a list of queries could be executed by the same engine instance. If a Json array of query is passed, it did not work. For my experiment, i was using apollo-link-batch-http and as expected the parser complained about "query" be present in the request.

2. Nested mutation: in what capacity that this feature is currently supported or is it in the roadmap?

Thanks for your time and keep up with great work. Cheers

**Comment by tlil** [comment]
Hi @GOVYANSONG, sorry I didn't respond to this sooner. Did you find what you were looking for?

(1) You can construct a mutation request with multiple mutation operations like this:

```graphql
mutation RunMultipleMutations {
  doSomething(...)
  doAnotherThing(...)
  doAThirdThing(...)
}
```

which will result in a response:

```json
{
  "doSomething": <result-of-first-mutation>,
  "doAnotherThing": <result-of-first-mutation>,
  "doAThingThing": <result-of-first-mutation>,
}
```

(2) Not supported, and not in the standard currently implemented by graphql-dotnet/graphql-dotnet and graphql-dotnet/conventions.
