### ISSUE TITLE
How to use with graphql-dotnet/server

### ISSUE THREAD

**Issue by timpur** [graphql-dotnet/conventions#99]
Hi im wondering how i can use with https://github.com/graphql-dotnet/server

I believe all i need to do with some how create a Query:

How do i gererate a `IObjectGraphType`??

Should i be using `GraphTypeAdapter` ?? 

Wondering best how to connect the 2 libs :)

``` c#
public class ChatSchema : Schema
{
    public ChatSchema(IChat chat) 
    {
        Query = new ChatQuery(chat); /// how to create this ????
        Mutation = new ChatMutation(chat);
        Subscription = new ChatSubscriptions(chat);
    }
}
```

Thanks

**Comment by RehanSaeed** [comment]
Also wanted to ask if there are any limitations to using this library, over `graphql-dotnet/server` on it's own.

**Comment by snys98** [comment]
Also wondering why this repo seems so different from `graphql-dotnet`. Holy I JUST CAN'T FIND THE `ISchema`...

**Comment by tlil** [comment]
@snys98 that comes across as rude and shallow, which makes me inclined not to answer your questions!

It's different because... well, guess what, it's different. It's trying to solve another problem, consequently in a different way. ...

**Comment by tlil** [comment]
@timpur and @RehanSaeed - will check back in and reply to your questions a bit later. Sorry for the late reply.

**Comment by timpur** [comment]
Thanks

**Comment by tlil** [comment]
@timpur To use subscriptions we'd need to get #89 done first, unfortunately.

As for your question about deriving a schema, you could use `GraphTypeAdapter.DeriveSchema`. More specifically, see how it's done in `test/Tests/Templates/ConstructionTestBase.cs`. Let me know if that helps. :-)

**Comment by timpur** [comment]
Thanks ill have a look

**Comment by snys98** [comment]
Sorry for my comment above, but I'm not mean to be _rude and shadow_. I use these upper case words to express my depress of spending many time with no result. Any way, thx for your efforts :) 👍 @tlil 

And maybe this is how this lib work with `graphql/server` @timpur 
``` c#
public void ConfigureServices(IServiceCollection services)
{
    var typeAdapter = new GraphTypeAdapter();
    var constructor = new SchemaConstructor<ISchema, IGraphType>(typeAdapter);
    var schema = constructor.Build(typeof(SchemaDefinition<GraphQLExampleQuery, GraphQLExampleMutation, GraphQLExampleSubscription>));
    services.AddSingleton<ISchema>(schema);
    // ... some other code
}
```

And please note this is not the final best practice~
